### ISSUE TITLE
Support podman-remote for execution environments when using toolbox on Fedora Silverblue.

### ISSUE THREAD

**Issue by ptoal** [ansible/vscode-ansible#1020]
### Problem

After moving to Fedora Silverblue, I've struggled to get VSCode set up for developing Ansible playbooks.  I'm pretty close now, with help from this repo: https://github.com/owtaylor/toolbox-vscode.

One thing I'm not able to do, yet, is get execution environments working, as it's not possible to execute podman from within a container.  So the idea is to use podman.sock to allow podman-remote to run the containers in the host system.

What we need is a way to specify that the extension should use the `podman-remote` command, rather than `podman`.

I took a stab at modifying the vscode-ansible plugin, and the ansible-language-server (as that's where the podman command is built), but I've been unable to get my custom build of the extension to work.

### Solution

Allow the user to configure the extension to use the podman-remote command to execute the ansible-language-server and playbooks.

**Comment by ssbarnea** [comment]
@priyamsahoo Please investigate this one.

**Comment by Qalthos** [comment]
Hey, this is an interesting request, but one we might not be able to do too much about for the reasons it sounds like you've already discovered.

That said, I would like to at least understand how your setup was put together so we can better understand the issue. I'm assuming VSCode was installed on some form of container and you were looking to use podman-remote to call on the host system's podman, but any more details you could give might help us down the line.

**Comment by Qalthos** [comment]
At the moment we don't support this environment, but if anyone wants to propose a PR to work around this, we will accept it gladly.
