### ISSUE TITLE
[RFE] Add a check box in creator view to install collection in a editable way

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#1083]
### Problem

Currently after the new collection is scaffolded user will have to goto command line and run ADE (https://ansible.readthedocs.io/projects/dev-environment/) by changing to the new collection root directory and installing it in editable format. Having a 

### Solution

In the creator view add a checkbox item to allow users to select if they want to install the collection in editable format after it is scaffolded. Having a checkbox in the creator view with pointers to ADE doc will help provide a guided experience for users new to this tools 

### Alternatives

Alternative is command line which requires user to understand what is ADE and how to run it.

**Comment by cidrblock** [comment]
Note: The destination path for the new collection creator makes will change.  https://github.com/ansible/ansible-creator/issues/92
