### ISSUE TITLE
Getting "Cannot set properties of undefined (setting 'currentModelValue')" error message while trying to connect in Lightspeed

### ISSUE THREAD

**Issue by AlexonOliveiraRH** [ansible/vscode-ansible#1084]
### Summary

I'm not being able to login with Ansible Lightspeed using the Red Hat Ansible extension due a `Cannot set properties of undefined (setting 'currentModelValue')` error message.

If uninstall VSCode and install it again, it works, but I can't open any folder or workspace before trying to connect to Lightspeed the first time. If I open any folder/workspace afterwards, it stops working and I cannot connect to it again.

Environment info:

```
$ sudo rpm -qa | grep ^code
code-1.86.0-1706698221.el8.x86_64

$ cat /etc/system-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

$ uname -r
4.18.0-513.11.1.el8_9.x86_64
```

Steps to reproduce it:

1. If you have VSCode installed, uninstall it and remove every remain.
2. Reinstall VSCode and install/enable Red Hat Ansible extension.
3. Before open any folder or workspace, try to connect to Ansible Lightspeed. It should work.
4. Now open any folder or workspace.
5. Get back to the Ansible Lightspeed connector. It will be disconnected.
6. Try to connect again and it won't be possible. You'll get the described error message.

![Screenshot from 2024-02-07 10-45-49](https://github.com/ansible/vscode-ansible/assets/45946599/0477dbe1-d567-4402-92c5-4a9651ead297)
![Screenshot from 2024-02-07 10-46-13](https://github.com/ansible/vscode-ansible/assets/45946599/da455e8c-d964-47dc-bbef-a5fd55ed7f12)
![Screenshot from 2024-02-07 10-46-57](https://github.com/ansible/vscode-ansible/assets/45946599/24fb1567-0b7b-44cb-b5ca-faa0aa806a73)
![Screenshot from 2024-02-07 10-55-14](https://github.com/ansible/vscode-ansible/assets/45946599/b785e8cd-c480-4ce4-a97d-82aaa0d3306d)

### Extension version

v2.10.130

### VS Code version

1.86.0

### Ansible Version

```shell
$ ansible --version
ansible [core 2.13.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/alolivei/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/alolivei/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/alolivei/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/alolivei/.local/bin/ansible
  python version = 3.8.17 (default, Aug 10 2023, 12:50:17) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

```
$ sudo rpm -qa | grep ^code
code-1.86.0-1706698221.el8.x86_64

$ sudo rpm -qa | grep ^ansible
ansible-core-2.15.3-1.el8.x86_64
ansible-8.3.0-1.el8.noarch

$ cat /etc/system-release
Red Hat Enterprise Linux release 8.9 (Ootpa)

$ uname -r
4.18.0-513.11.1.el8_9.x86_64
```

**Comment by TamiTakamiya** [comment]
@AlexonOliveiraRH This looks like the issue we fixed with #1076.  I am planning to release a new version of the extension tomorrow, which will include the fix.

**Comment by AlexonOliveiraRH** [comment]
> @AlexonOliveiraRH This looks like the issue we fixed with #1076. I am planning to release a new version of the extension tomorrow, which will include the fix.

Hey @TamiTakamiya. Thank you for the reply. Yeah, I'm aware of that fix. In fact, @goneri reproduced that based on my previous scenario to reach the bug that originated that fix. But this scenario I'm presenting now is a bit different from the one that originated that fix. That bug was due a racing condition, if I'm not mistaken. This one doesn't not have the same race condition, since I'm facing it even after uninstall and install VSCode.

**Comment by AlexonOliveiraRH** [comment]
![Screenshot from 2024-02-07 14-23-46](https://github.com/ansible/vscode-ansible/assets/45946599/6d8f7a8f-4c2b-47dc-a6ba-cf7f52d915e7)

**Comment by AlexonOliveiraRH** [comment]
```
$ ls -la /home/alolivei/Documents/MyLab/OCP3.11-VMware/Production_Environment/ansible/ldap_template
total 36
drwxrwxr-x. 2 alolivei alolivei  203 ago 22  2022 .
drwxrwxr-x. 4 alolivei alolivei   76 ago 22  2022 ..
-rw-rw-r--. 1 alolivei alolivei  536 ago 22  2022 ldap-config.yaml
-rw-rw-r--. 1 alolivei alolivei 1540 ago 22  2022 ldap-sync-all.yaml
-rw-rw-r--. 1 alolivei alolivei 1568 ago 22  2022 ldap-sync-terceiros.yaml
-rw-rw-r--. 1 alolivei alolivei 1593 ago 22  2022 ldap-sync.yaml
-rw-rw-r--. 1 alolivei alolivei 1615 ago 22  2022 ldap-sync.yaml.bkp
-rw-rw-r--. 1 alolivei alolivei   24 ago 22  2022 master
-rw-rw-r--. 1 alolivei alolivei  239 ago 22  2022 role-grp.sh
-rw-rw-r--. 1 alolivei alolivei  858 ago 22  2022 roles
-rw-rw-r--. 1 alolivei alolivei  683 ago 22  2022 whitelist.txt

$ ls -la /home/alolivei/Documents/MyLab/OCP3.11-VMware/Production_Environment/ansible/ldap_template/roles
-rw-rw-r--. 1 alolivei alolivei 858 ago 22  2022 /home/alolivei/Documents/MyLab/OCP3.11-VMware/Production_Environment/ansible/ldap_template/roles

$ cd /home/alolivei/Documents/MyLab/OCP3.11-VMware/Production_Environment/ansible/ldap_template/

$ mv roles roles_

$ ll
total 36
-rw-rw-r--. 1 alolivei alolivei  536 ago 22  2022 ldap-config.yaml
-rw-rw-r--. 1 alolivei alolivei 1540 ago 22  2022 ldap-sync-all.yaml
-rw-rw-r--. 1 alolivei alolivei 1568 ago 22  2022 ldap-sync-terceiros.yaml
-rw-rw-r--. 1 alolivei alolivei 1593 ago 22  2022 ldap-sync.yaml
-rw-rw-r--. 1 alolivei alolivei 1615 ago 22  2022 ldap-sync.yaml.bkp
-rw-rw-r--. 1 alolivei alolivei   24 ago 22  2022 master
-rw-rw-r--. 1 alolivei alolivei  239 ago 22  2022 role-grp.sh
-rw-rw-r--. 1 alolivei alolivei  858 ago 22  2022 roles_
-rw-rw-r--. 1 alolivei alolivei  683 ago 22  2022 whitelist.txt
```

**Comment by AlexonOliveiraRH** [comment]
![Screenshot from 2024-02-07 15-24-04](https://github.com/ansible/vscode-ansible/assets/45946599/b0cc3201-d3c4-4771-92c3-0fb5866f4160)

**Comment by AlexonOliveiraRH** [comment]
So, with @TamiTakamiya and @goneri help (++ to you both), I managed to identify this is another bug indeed and how to fix it. As you can see from the screenshot above, I'm now being able to connect after running the steps of my other previous comment.

Can you take from here, fellows?

**Comment by goneri** [comment]
Thank you @AlexonOliveiraRH. I've got a fix working, I just need to prepare some unit-tests.
