### ISSUE TITLE
Code Actions (quick fixes) for ansible-lint findings

### ISSUE THREAD

**Issue by tlourey** [ansible/vscode-ansible#1100]
### Problem

Ansible-lint findings in problems tab don't provide quick fix code actions

### Solution

Support Quick Fix Code Actions in Ansible Extension for VS Code

### Additional context

Refer: 
https://code.visualstudio.com/Docs/editor/editingevolved#_code-action
https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings

**Comment by ssbarnea** [comment]
@tlourey That seems like a wonderful suggestion but AFAIK we currently do not have anything planned in this direction. Still, if you can come up with PR that adds support for it, you will have all my support for including it in the extension.

**Comment by tlourey** [comment]
Hi @ssbarnea , unfortunately that is far beyond my skill set. 

I'm lead to believe the extension developer _just_ need to pass extra information when passing back problems (sounds easy! 😂). [Markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) might be a good one to look as an example of what I'm suggesting. 

I just know using the quick fix button for listed problems when working on PowerShell or Markdown (with the markdown lint extension above) is massive timesaver and help so I thought id suggest it. Might be something for the roadmap!

**Comment by priyamsahoo** [comment]
Hi @tlourey, you can use the `ansible.validation.lint.arguments` setting and add `--fix` in it. This will automatically fix the lint errors (that support fixing) in your playbook/task files.

**Comment by tlourey** [comment]
Thanks @priyamsahoo.

@ssbarnea does this seem like something you add into the vscode extension?

**Comment by priyamsahoo** [comment]
@tlourey, I am closing this issue as we do not plan to add this feature anytime soon, mainly because this can already be achieved using the arguments settings for ansible lint in the extension.
