### ISSUE TITLE
Adopt ansible-language-server into vscode-ansible repository

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#1134]
During a meeting between the most active contributors to both repositories, we decided to merge the vscode-ansible and the ansible-language-server back into a single github repository, while keeping the ability to release ALS separately.

This will greatly improve the development speed for this project, as it would allow us to make more atomic changes and release them with less effort. Both human and CI/CD testing will be simplified.

Other side effect benefits would be making triage of community issues much easier as it is very hard to identify if an issue is within the client side of the extension or its language-server. Also this should make it much easier for external contributor to make pull requests it would involve changes to a single repository.

To be implemented gradually to minimize the effect on currently opened pull requests.
 
## Checklist

- [x] Move ALS code
- [x] Merge ALS documentation into extension
- [x] Move all tickets and discussions from ALS into extension repository
- [x] Archive ALS github repository while pointing that the code is now inside extension repository
- [x] Ensure ALS tests do run on CI
- [ ] Remove redundant CI/CD config from ALS folder
- [ ] Update release drafter to highlight which changes are specific to the language server
- [ ] Update Github pipelines to allow a manual triggering of publishing of ALS to npm.org

Closes: AAP-21793

**Comment by ssbarnea** [comment]
I am trying to use the process described at https://gfscott.com/blog/merge-git-repos-and-keep-commit-history/ in order to keep the change history.

**Comment by mehalter** [comment]
@ssbarnea every since this change and the first release of `ansible-language-server` from this repo (v1.2.2) the `ansible-language-server` cli is broken. When I simply do `npm install @ansible/ansible-language-server` and then try and run:

```sh
ansible-language-server --stdio
```

I get the following error:

```
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module './ansibleLanguageService'
Require stack:
- /home/micah/test/node_modules/@ansible/ansible-language-server/out/server/src/server.js
- /home/micah/test/node_modules/@ansible/ansible-language-server/bin/ansible-language-server
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/micah/test/node_modules/@ansible/ansible-language-server/out/server/src/server.js:5:34)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/micah/test/node_modules/@ansible/ansible-language-server/out/server/src/server.js',
    '/home/micah/test/node_modules/@ansible/ansible-language-server/bin/ansible-language-server'
  ]
}
```
