### ISSUE TITLE
Add instructions for vim-lsp

### ISSUE THREAD

**Issue by petRUShka** [ansible/vscode-ansible#1137]
### Problem

There is quite popular vim/nvim plugin [vim-lsp](https://github.com/prabirshrestha/vim-lsp) for LSP support.

There should be very useful to have instructions to add support of [ansible-language-server](https://github.com/ansible/ansible-language-server) to vim-lsp.

### Solution

Add instructions or add push request to vim-lsp (see also https://github.com/mattn/vim-lsp-settings/issues/666).

**Comment by vzsoares** [comment]
I ended up with:
```lua
-- init ansible language server config
require('lspconfig').ansiblels.setup {}
-- configure filetype
vim.filetype.add({ pattern = { [".*%.ansible%..*"] = "yaml.ansible" } }) -- this will match playboook.ansible.yaml
```

**Comment by ssbarnea** [comment]
I am closing this because our team will not be able to work on this. Still, any PR that documents or even adds some basic integration testing for other IDEs, will be welcomed.
