### ISSUE TITLE
Current release does not highlight, main does.

### ISSUE THREAD

**Issue by kjoyce77** [ansible/vscode-ansible#1138]
### Summary

Hover help, highlighting, and task-level autocomplete is not working for me on the current release of the VSCode extension.  I'm not sure how to even see the errors in the language server itself and I don't seem to see anything useful from the debugging on the plugin.

Additional background strangeness.  This is reproducible in VSCade 1.85.2 as well -- but only on our RHEL9 servers.  The Oracle Linux 7 servers we now have to move off of actually work.

If I run according to the development.md directions and checkout the tags for the releases this is reproduced.  However, if I checkout out ansible-language-server:main then everything works as expected.  So perhaps this is just a 'please clean up your main and release a new version' request.  Of course if you have a pre-release tag please have me test that before going to full release.  Thank you!!

Also: this is the `npm install .` output on v1.2.1
```
[ak1usr1398@lzlbdvjp1004 ansible-language-server]$ npm install .
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

> @ansible/ansible-language-server@1.2.1 prepare
> npm run compile


> @ansible/ansible-language-server@1.2.1 compile
> tsc -p .


added 601 packages, removed 470 packages, and audited 602 packages in 45s

3 vulnerabilities (1 moderate, 1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

### Extension version

v1.2.1

### VS Code version

1.86

### Ansible Version

```shell
config file = /users/ak1usr1398/projects/vscode-ansible/examples/ansible.cfg
  configured module search path = ['/users/ak1usr1398/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /users/ak1usr1398/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.10 (main, Feb  1 2024, 22:53:29) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/local/bin/python3.10)
  jinja version = 3.1.3
  libyaml = True
```

### OS / Environment

OS:
kernel: 5.14.0-362.18.1.el9_3.x86_64
release: Red Hat Enterprise Linux release 9.3 (Plow)

Remote extension: vscode-ansible v2.10

[ak1usr1398@lzlbdvjp1004 examples]$ ansible-lint --version
ansible-lint 6.22.2 using ansible-core:2.16.3 ansible-compat:4.1.11 ruamel-yaml:0.18.5 ruamel-yaml-clib:0.2.8

[ak1usr1398@lzlbdvjp1004 ansible-language-server]$ node --version
v18.17.1

### Relevant log output

```shell
[Trace - 12:08:18 PM] Sending request 'textDocument/hover - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///users/ak1usr1398/projects/vscode-ansible/examples/playbooks/play2.yml"
    },
    "position": {
        "line": 5,
        "character": 24
    }
}


[Trace - 12:08:18 PM] Received response 'textDocument/hover - (3)' in 10ms.
No result returned.
```

**Comment by ssbarnea** [comment]
Closing due to lack of finding a way to reproduce with current versions.
