### ISSUE TITLE
hardcoded python3 is used as executable instead of ansible.python.interpreterPath

### ISSUE THREAD

**Issue by zalent** [ansible/vscode-ansible#1140]
### Summary

There is **_ansible.python.interpreterPath_** setting but it's not getting used. There are multiple hardcoded python3 executables launches which should not be used when **_ansible.python.interpreterPath_** is set.
Few examples:
https://github.com/ansible/ansible-language-server/blob/75a39bb16eb3b8767d7d719d61fb13b2c86f6215/src/services/ansibleConfig.ts#L85
https://github.com/ansible/ansible-language-server/blob/75a39bb16eb3b8767d7d719d61fb13b2c86f6215/src/utils/getAnsibleMetaData.ts#L114
https://github.com/ansible/ansible-language-server/blob/75a39bb16eb3b8767d7d719d61fb13b2c86f6215/src/utils/getAnsibleMetaData.ts#L128
https://github.com/ansible/ansible-language-server/blob/75a39bb16eb3b8767d7d719d61fb13b2c86f6215/src/utils/commandRunner.ts#L37

### Extension version

2.9.118

### VS Code version

1.86.0

### Ansible Version

```shell
❯ ansible --version
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/home/ans/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ans/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/ans/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ans/.local/bin/ansible
  python version = 3.11.5 (main, Sep  7 2023, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Win 11 WSL2 Centos 9 Stream Python 3.11, default system python3 points to python3.9

### Relevant log output

```shell
Ansible meta data
ansible information:

core version: 2.16.0

location: ~/.local/lib/python3.11/site-packages/ansible

config file path: /mnt/c/Users/ans/AppData/Local/Programs/Microsoft VS Code Insiders/None

collections location:

~/.ansible/collections
/usr/share/ansible/collections
/usr/lib64/python39.zip
/usr/lib64/python3.9
/usr/lib64/python3.9/lib-dynload
~/.local/lib/python3.9/site-packages
/usr/lib64/python3.9/site-packages
/usr/lib/python3.9/site-packages
modules location:

~/.ansible/plugins/modules
/usr/share/ansible/plugins/modules
~/.local/lib/python3.11/site-packages/ansible/modules
default host list path:

/etc/ansible/hosts
python information:

version: 3.9.18

location: /usr/bin/python3

ansible-lint information:

version: 6.22.1
```

**Comment by ssbarnea** [comment]
This seems like a good reason to get surprises from extension and should be easy to fix.

**Comment by audgirka** [comment]
This is already taken care of [here](https://github.com/ansible/vscode-ansible/blob/main/packages/ansible-language-server/src/utils/commandRunner.ts#L36)

We only get the python interpreter path from config and not the executable name which is why we are just passing `python3`.
It tells the command runner to execute `python3` from the config interpreter path

**Comment by tomaxsas** [comment]
i'm seeing this in the config. for me its issue, and that code is not taken care of, as i specifically pointed locations where pythno3 is used no matter what.
![image](https://github.com/user-attachments/assets/8a9e6415-5787-4f59-b13d-17b860653185)

**Comment by tomaxsas** [comment]
> This is already taken care of [here](https://github.com/ansible/vscode-ansible/blob/main/packages/ansible-language-server/src/utils/commandRunner.ts#L36)
> 
> We only get the python interpreter path from config and not the executable name which is why we are just passing `python3`. It tells the command runner to execute `python3` from the config interpreter path

if you look closely you will see that it does not use it in every case. if it would i wont be seeing these
![image](https://github.com/user-attachments/assets/5b428709-ff78-41bc-950a-4376a431f183)

**Comment by ph25sl** [comment]
I'm seeing similar whereby it's still picking up `/usr/bin/python3` from somewhere despite Python environment set to Python 3.11 (/usr/bin/python3.11). The interpreter path is also set to /usr/bin/python3.11. 

This causes a mix-match:
> Ansible CLI (2.12.10) and python module (2.15.13) versions do not match. This indicates a broken execution environment.

Running the exact command it complains about for linting at the CLI on the server works correctly. 

Command failed: /home/<user>/.local/bin/ansible-lint -c "/home/<user>/ansible/.ansible-lint" --offline --nocolor -f codeclimate "/home/<user>/ansible/path_to_file.yml" 

Additionally, creating a Python venv for 3.11  works around the issue. 

<img width="689" alt="Image" src="https://github.com/user-attachments/assets/3d06da26-4c40-4cbb-8530-d42399dfdf3f" />

<img width="576" alt="Image" src="https://github.com/user-attachments/assets/56933be9-b29a-4060-81ab-1ecd7d207019" />
