### ISSUE TITLE
ansible variable resolution with live preview

### ISSUE THREAD

**Issue by rafi0101** [ansible/vscode-ansible#1221]
### Problem

If you have nice colleagues who use individual and nested variables for everything and you look at the Ansible role/task, you can't find your way around at first. You always have to search for a long time where which variable is defined and then usually forget it 1 minute later. Here is an example of what I mean, especially if the variables are in different lines/files. If I use tomee_log_file somewhere, I have to add up 3 variables in my head (not that I can't do that), but if you now have a task with 3 such variable constructs, it gets pretty confusing:

![image](https://github.com/ansible/vscode-ansible/assets/43086854/d3b129fd-b60c-4a6d-8058-d8f6eb2caea8)

### Solution

How about if the vs-code extension could resolve the variable for you and then either on mouseover or to the right of it (like git, but git should be preserved) resolve the variable completely and then return e.g. "/var/log/tomee/tomee.log". so I know immediately what is behind the variable.

It would be cool if this would work with yaml and jinja. But I think it needs a separate feature request for jinja in their project.

If the resolved variable only shows 1 result, only that should be shown, but if e.g. the variable is different per group/host, all possibilities should be resolved. Maybe limited to a few and sorted/grouped if there are several identical ones.

**Comment by audgirka** [comment]
Ansible vars can only be resolved at runtime and it is not practically possible to implement in a way that would provide variable resolution at all levels.
