### ISSUE TITLE
Ansible-language-server npm package 1.2.2 is missing core files

### ISSUE THREAD

**Issue by kartikvashistha** [ansible/vscode-ansible#1266]
### Summary

Hi,

It looks like version `1.2.2` for `ansible-language-server`'s npm package is missing some core files that prevents the LSP from starting up for me on neovim. From what I can tell, all files apart from the `server.js` are missing in `1.2.2`. 

I'm suspecting this due to the re-writes that have been happening under the `packages/ansible-language-server` directory ( maybe due to the rewrite of the release script?) which accidentally prevented the necessary files from being packaged.  As such, whenever I try to connect to the lsp server, it fails due to an error in sourcing the files, as shown in the logs attached.

For the time being, I can revert back to the previous 1.2.1 version to unblock myself, but I'm guessing we would probably need 1.2.3 as soon as possible.

For your reference, you can compare both the versions here:
1.2.1: https://www.npmjs.com/package/@ansible/ansible-language-server/v/1.2.1?activeTab=code
1.2.2: https://www.npmjs.com/package/@ansible/ansible-language-server/v/1.2.2?activeTab=code

Thanks!

### Extension version

1.2.2

### VS Code version

N/A

### Ansible Version

```shell
ansible [core 2.16.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kartik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/kartik/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.12.3 (main, Apr 17 2024, 00:00:00) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.3
  libyaml = True
```

### OS / Environment

Fedora 40

### Relevant log output

```shell
[START][2024-04-22 16:17:55] LSP logging initiated
[ERROR][2024-04-22 16:17:55] .../vim/lsp/rpc.lua:734	"rpc"	"ansible-language-server"	"stderr"	"node:internal/modules/cjs/loader:1146\n  throw err;\n  ^\n\nError: Cannot find module './ansibleLanguageService'\nRequire stack:\n- /home/kartik/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js\n- /home/kartik/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/bin/ansible-language-server\n    at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)\n    at Module._load (node:internal/modules/cjs/loader:984:27)\n    at Module.require (node:internal/modules/cjs/loader:1231:19)\n    at require (node:internal/modules/helpers:179:18)\n    at Object.<anonymous> (/home/kartik/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js:5:34)\n    at Module._compile (node:internal/modules/cjs/loader:1369:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)\n    at Module.load (node:internal/modules/cjs/loader:1206:32)\n    at Module._load (node:internal/modules/cjs/loader:1022:12)\n    at Module.require (node:internal/modules/cjs/loader:1231:19) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/kartik/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/server.js',\n    '/home/kartik/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/bin/ansible-language-server'\n  ]\n}\n\nNode.js v20.12.2\n"
```

**Comment by ssbarnea** [comment]
@kartikvashistha I am working to fix this but I might need some help to implement a regression test. It would be very useful to me to have some ts code that I can run to validate the package, basically to start the language server and stop it.
