### ISSUE TITLE
Getting error when specify ansible-lint executable in WSL2

### ISSUE THREAD

**Issue by markatdxb** [ansible/vscode-ansible#127]
**Describe the bug**
Well i dont know if its a bug but i followed the guide to install lint but still getting error when typing in the path of ansible-lint in config file 

ansible-lint is installed in my /.local/bin/ansible-lint
PATH is also correct as i can execute the ansible-lint from anywhere 
what else can be wrong ?

**To Reproduce**

**Expected behavior**

**Platform:**

im running WIndows 10 with WSL2 and Ubuntu 20.04 

**Additional context**

**Comment by webknjaz** [comment]
Please fill out the issue form with STR. Also, replace the placeholder text with actual information.

**Comment by webknjaz** [comment]
Note that to get community support it's best to start discussions, not file issues.

**Comment by markatdxb** [comment]
Sorry my bad about this issue - i actually thought its an issue with the plugin
