### ISSUE TITLE
Allow to set custom PATH for the execution of this extension

### ISSUE THREAD

**Issue by ChristianCiach** [ansible/vscode-ansible#130]
Please see my comments here: https://github.com/ansible-community/vscode-ansible/issues/129#issuecomment-872506805

This extension allows to configure the path to the `ansible-lint` executable, but this is not enough. `ansible-lint` calls the `ansible` executable and expects this to be on the global `PATH`:

https://github.com/ansible-community/ansible-lint/blob/57a6d5bd1cb5fb85fdda040d0165d8a75c8f43f1/src/ansiblelint/config.py#L146

The same is probably true for the execution of `yamllint`.

So, what's the point of configuring the full path to `ansible-lint` if `ansible` and `yamllint` are expected to be on the global `PATH`? Why not just make the same assumption for the `ansible-lint` executable?

Instead of (or in addition to) making `ansible.validate.executablePath` and `ansible.vault.executablePath` configurable, I think it would be better to have another setting to configure a custom `PATH` that is valid for the whole extension and is also used when `ansible-lint` calls `ansible` (as shown above).

This setting could be called something like `ansible.path` and should be configurable per-workspace and per-folder, so that is can be adjusted for local venv or conda-environments. The value of this setting should be used instead or (probably better) be prepended to the global `PATH` of the vscode process. 

As described in https://github.com/ansible-community/vscode-ansible/issues/129#issuecomment-872506805, setting a custom `PATH` when calling `ansible-lint` fixes the issue where `ansible` and `yamllint` are not on the global `PATH`.

**Comment by ssbarnea** [comment]
I would welcome a PR that does this, especially if that ansible.path would be prepended to system PATH before running commands. Undefined it would mean nothing to be added.

**Comment by ChristianCiach** [comment]
I had an idea while writing a [custom task](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks) for yamllint. The task looks like this:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "yamllint",
            "type": "shell",
            "command": "yamllint",
            "args": [
                "-f",
                "parsable",
                "${relativeFile}"
            ],
            "isBackground": false,
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "echo": true,
                "reveal": "silent",
                "focus": false,
                "panel": "dedicated",
                "showReuseMessage": false,
                "clear": true,
                "revealProblems": "onProblem"
            },
            "problemMatcher": {
                "source": "yamllint",
                "owner": "yaml",
                "applyTo": "allDocuments",
                "fileLocation": ["relative", "${workspaceFolder}"],
                "pattern": {
                    "regexp": "^(.*):(\\d+):(\\d+):\\s+\\[(warning|error)\\]\\s+(.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "severity": 4,
                    "message": 5
                }
            }
        }
    ]
}
```

As you can see, I use `"type": "shell",` instead of `"type": "process"`. By doing this, the task gets executed inside a dedicated terminal (which is visible in the "terminal" tab). Because the setting `python.terminal.activateEnvironment` of the python-extension defaults to `true`, the terminal will automatically activate the virtual environment (thus, extending the PATH) before executing the task.

This can surely also be done in extensions, not just tasks, right? So, instead of using `child_process` to call ansible-lint, maybe you could do the equivalent of what I am doing in my task. This would also have the huge advantage that the user can actually see the errors that are returned by ansible-lint: You can just open the terminal to see the output. By using `"reveal": "silent"` (as shown above) the terminal only gets revealed if ansible-lint exists with an error (exit code other than 0).

**Comment by ssbarnea** [comment]
Closing because the original problem cannot be reporduced anymore and because we do not plan to add support for custom PATHs, mainly as this would not really work with containers.
