### ISSUE TITLE
[vscode client] Add support for running ansible-playbook and ansible-navigator from IDE browser

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#132]
To provide entry for running playbooks and drop-down option can be supported to trigger either `ansible-playbook` or `anisble-navigator` in the terminal from IDE browser window.
In the dropdown menu add `ansible-playbook` and `ansible-navigator` options and trigger the run for playbook within the terminal

**Comment by ssbarnea** [comment]
Is this about adding an option that is similar to what happens with Python files when you right click them on sidebar? For them I see "Run Current File in Interactive Window".

To avoid cluttering the UI we would likely make the runner configurable, so the user can decide if they want to use plain ansible-playbook or ansible-navigator in settings. That will likely address other execution options.

**Comment by webknjaz** [comment]
> Is this about adding an option that is similar to what happens with Python files when you right click them on sidebar? For them I see "Run Current File in Interactive Window".

Yes
