### ISSUE TITLE
Autocomplete not working properly in tasks file within role

### ISSUE THREAD

**Issue by jeinwag** [ansible/vscode-ansible#133]
Autocomplete is not working properly when I'm editing a tasks file within a role, I only get suggestions for generic task parameters:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/9193234/125603085-85ac7011-7b39-4b32-a542-3496c885d838.png">

It does work in a top-level playbook however:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/9193234/125603233-bd949d1a-2ed9-4aa0-a642-e969d2a10be4.png">

**To Reproduce**
Create a new role and start editing a tasks file.

**Expected behavior**
I expect to get full autocomplete suggestions when editing the tasks file.

**Platform:**
 - OS: macOS 11.4
 - VSCode: Version: 1.58.1 Commit: 2aeda6b18e13c4f4f9edf6667158a6b8d408874
 - Ansible Language Extension 0.4.5

**Comment by jeinwag** [comment]
Ok, I did some more digging: Turns out VS Code is using a completely different schema for the playbook (not from the https://github.com/ansible-community/schemas repository), no idea why.

But the problem remains: I can't get any suggestions for modules in the tasks file, even though they are in the schema that's being used (https://github.com/ansible-community/schemas/blob/main/f/ansible-tasks.json).

**Comment by ssbarnea** [comment]
This is kinda expected/known and it will take some time to be fixed. We discovered that JSON schema does not scale to the size of the data model we have on Ansible, especially when Ansible has all community modules. The plan is to replace current use of YAML extension with a custom language server for Ansible, which would not have such limitations.

Still, that is a major piece of work and I do suspect it will take a couple of months to complete.

**Comment by jeinwag** [comment]
Thanks for the heads up! I can see that developing a new language server for Ansible is no small feat.

**Comment by jeinwag** [comment]
I'm closing this issue since I can see the language server is already on the horizon. Thanks for the great work!

**Comment by ssbarnea** [comment]
Probably we will close most existing bugs when we make the first release with the language server as they will no longer apply.

**Comment by karthicraghupathi** [comment]
I'm experiencing the same problem. Has the language server been released yet? If not, is there a relevant issue I can follow?
