### ISSUE TITLE
Add e2e integration testing for extension

### ISSUE THREAD

**Issue by webknjaz** [ansible/vscode-ansible#139]
**Is your feature request related to a problem? Please describe.**

No tests.

**Describe the solution you'd like**

Tests must exist.

**Describe alternatives you've considered**

Giving up on quality.

**Additional context**

There's not many good examples of writing integration tests for VS Code extensions so here's some pointers I've found:
- https://developers.redhat.com/blog/2019/11/18/new-tools-for-automating-end-to-end-tests-for-vs-code-extensions
- https://github.com/redhat-developer/vscode-extension-tester/wiki
- https://github.com/redhat-developer/vscode-extension-tester
- https://vscode.rocks/testing/
- https://github.com/mlewand-org/vscode-test-content
- https://viatsko.github.io/awesome-vscode/#resources-for-extension-developers

**Comment by webknjaz** [comment]
I don't think this should be closed. There's no test examples, it's not solved.

**Comment by ssbarnea** [comment]
True, it should be open until we finish setting the framework and a minimal battery of testing, so others can easily add more of them while adding other features of bugfixes.

`vscode-extension-tester` is already used now and it looks promising.
