### ISSUE TITLE
Ansible Lightspeed view should be more informative when it's not enabled

### ISSUE THREAD

**Issue by svor** [ansible/vscode-ansible#1442]
### Summary

When Ansible Lighspeed is disabled, I see this view:
![screenshot-nimbusweb me-2024 07 23-10_49_17](https://github.com/user-attachments/assets/7f0cfd09-a8cd-41b7-83bc-bd7e5288be1d)
 It would be better to see more informative message instead of undefined. Maybe a suggestion to enable Ansible Lightspeed in Settings.   

### Extension version

v24.8.3

### VS Code version

1.91.0

### Ansible Version

```shell
ansible [core 2.16.6]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections:/projects/ansible-devspaces-demo/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.5 (main, Sep 22 2023, 15:34:29) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)] (/usr/bin/python3.11)
  jinja version = 3.1.4
  libyaml = True
```

### OS / Environment

NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"

ansible-lint 24.2.3

**Comment by ssbarnea** [comment]
Seems related #1443

**Comment by TamiTakamiya** [comment]
@svor Thanks for reporting this issue. I could recreate it and started providing a fix.

**Comment by TamiTakamiya** [comment]
@svor The side panel was supposed to display the same text, which is displayed when Lightspeed is enabled:

![image](https://github.com/user-attachments/assets/89b70139-4df1-4470-8265-c95d03910706)

and user clicked the Connect  button an error message is poped up

![image](https://github.com/user-attachments/assets/6887c0ef-9799-445b-97d0-a182dcaf74c6)

I am going to fix the code to work in this way, which was working in the previous releases.

For showing more informative message like the suggestion to enable Ansible Lightspeed in Settings, I will open a separate isue tagged with enhancement.

**Comment by svor** [comment]
@TamiTakamiya thank you for the explanation.

Any reason why Ansible Lightspeed is not enabled by default?

**Comment by goneri** [comment]
@svor the completion service would trigger errors for the users with no subscription.
