### ISSUE TITLE
Updating vscode-extension-tester to 8.4.0 and the vscode version used during testing breaks tests

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#1464]
Seen on https://github.com/ansible/vscode-ansible/actions/runs/10160587251/job/28097290030?pr=1462#step:12:422 which updated 
```
NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-workbench"}
```

This is very unlikely to be caused by a regression with https://github.com/redhat-developer/vscode-extension-tester/releases/tag/v8.4.0 but more likely to be effect of switching vscode max version used for testing https://github.com/redhat-developer/vscode-extension-tester/pull/1400

This should be treated as very important, as it might indicate even runtime problems with current version of vscode.

**Comment by alisonlhart** [comment]
Possibly fixed in https://github.com/redhat-developer/vscode-extension-tester/pull/1485, will verify.

**Comment by alisonlhart** [comment]
The extester 8.6.0 release results in the same failure. 
https://github.com/alisonlhart/vscode-ansible/actions/runs/10585584457/job/29332508066?pr=3#step:14:323
Adding an update on the [issue](https://github.com/redhat-developer/vscode-extension-tester/issues/1452).
