### ISSUE TITLE
VScode missing yml icons

### ISSUE THREAD

**Issue by AllRWeak** [ansible/vscode-ansible#1520]
### Summary

When using the latest version (v24.8.4) of this extension the *.yml file icons are missing. The icons come back when switching to the previous version (v24.8.3). Might be related to this https://github.com/ansible/vscode-ansible/pull/1269
![Screenshot from 2024-08-23 12-35-45](https://github.com/user-attachments/assets/df286b6e-0eea-4c52-b71d-7e251e8f4dd4)
![Screenshot from 2024-08-23 12-40-29](https://github.com/user-attachments/assets/fb264124-28ca-4841-865b-33a8b5264d0e)

### Extension version

v24.8.4

### VS Code version

v1.92.2

### Ansible Version

```shell
ansible --version
ansible [core 2.17.3]
  config file = /home/user/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/user/ansible:/home/user/ansible
  executable location = /home/user/.venv/bin/ansible
  python version = 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] (/home/user/.venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### OS / Environment

cat /etc/os-release 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

**Comment by alisonlhart** [comment]
Adding this to our roadmap for resolution.

**Comment by GeorchW** [comment]
The issue seems to be that the file icon is not included in the final vsix bundle -- it should be under `/extension/images/ansible-fileicon.svg`. If I'm not mistaken, it just needs to be added to the `.vscodeignore` file to include it
