### ISSUE TITLE
[master] Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#158]
### Summary

When opening https://github.com/ansible-community/ansible-lint/blob/main/examples/galaxy.yml file and setting the type as `Ansible`, our extension reports: Cannot read property 'slice' of undefined

### Extension version

master

### VS Code version

1.58.2

### Ansible Version

```shell
-
```

### OS / Environment

-

### Relevant log output

```shell
[2021-08-03 14:33:39.534] [exthost] [warning] redhat.vscode-yaml - Code actions of kind 'quickfix 'requested but returned code action does not have a 'kind'. Code action will be dropped. Please set 'CodeAction.kind'.
[2021-08-03 14:33:40.653] [exthost] [warning] redhat.vscode-yaml - Code actions of kind 'quickfix 'requested but returned code action does not have a 'kind'. Code action will be dropped. Please set 'CodeAction.kind'.
```

**Comment by ssbarnea** [comment]
I am almost sure this comes from the language server because we have no call of slice inside the extension, but there are few ones on ALS.

**Comment by ganeshrn** [comment]
@ssbarnea I am not able to reproduce the issue. Please refer attached snapshot. 

<img width="1392" alt="Screen Shot 2021-09-30 at 2 05 17 PM" src="https://user-images.githubusercontent.com/5292461/135417837-90c08a5e-4f92-4507-8ae1-8977dc440176.png">


Can you please share detailed reproducers steps which you dev environment setup details and relevant snapshots.

**Comment by ssbarnea** [comment]
This popup appears like 5-10 seconds after vscode starts, the time needed for Ansible extension to fully initialize:

![](https://sbarnea.com/ss/Screen-Shot-2021-10-01-14-57-31.38.png)

As you can see the document already uses Ansible language.

Other observations:
* When vscode just opens a file (no workspace open) aka "violet status bar mode", extension does not give this error. Still, it does seem to provide any auto-complete activity and the ansible-lint errors are not recognized.
* When vscode has a workspace open (blue sidebar) the slice error message appears

I even tested is VSCodium with a fresh empty repo and the minimal set of extensions and the same error happens.

![](https://sbarnea.com/ss/Screen-Shot-2021-10-01-15-17-26.74.png)
