### ISSUE TITLE
Support configuring a custom path for the ansible-lint configuration file

### ISSUE THREAD

**Issue by ferrarimarco** [ansible/vscode-ansible#1609]
### Problem

This VS Code extension relies on the ansible-lint config file autodiscovery mechanism. It would be helpful if this extension supported setting a specific path to an ansible-lint configuration file.

### Solution

Add an option such as `ansible.validation.lint.configFilePath` that points to the ansible-lint configuration file.

### Alternatives

- Config file autodiscovery: works but forces a particular directory structure
- Symbolic links: fragile and not cross-platform

### Additional context

ansible-lint docs reference: https://ansible.readthedocs.io/projects/lint/usage/#using-commands

> -c CONFIG_FILE, --config-file CONFIG_FILE: Specify configuration file to use. By default it will look for '.ansible-lint', '.config/ansible-lint.yml', or '.config/ansible-lint.yaml'

Thanks!

**Comment by alisonlhart** [comment]
There is an existing way to do this in the extension, using the settings for ansible-lint arguments in the extension. You can pass in the path using `-c <path-to-config-file>` in that setting. 
Closing for that reason.

**Comment by ferrarimarco** [comment]
Thanks for the guidance, @alisonlhart !
