### ISSUE TITLE
ensure we pre-configure file associations to avoid conflicting with vscode-yaml extension

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#162]
We need to ensure that `vscode-ansible` extension can co-exist with `vscode-yaml` extension and that file using recommended naming and repository layout are automatically detected as `ansible` while the rest are detected a just `yaml`.

This can be achieve by using some smart `file.associations` inside settings.json, like below:

```json
    "files.associations": {
        "**/playbooks/*.yml": "ansible",
        "**/playbooks/*.yaml": "ansible"
    }
```

I tested and these settings take precedence over the file extension advertised by both extensions, which are quite general.

The tricky part is that extension cannot expose these inside its manifest and the only way to enable them is to modify user settings when it starts first time. Likely we would not want to override user settings with our own patterns, so it needs to a prompt: "Do you want to configure `file.associations` with ansible file patterns?"

We can extract a relatively complete list of file patterns from https://github.com/ansible-community/ansible-lint/blob/f2fae710c7ccf99e2db2056569d964564403066d/src/ansiblelint/config.py#L14-L58 as the linter already have logic for distinguishing between random yaml files and files owned by ansible.

**Comment by cidrblock** [comment]
+ `site.yml` `site.yaml` `main.yml` main.yaml` `tasks/` `collections/ansible_collections` `roles`

**Comment by Spacebjorn** [comment]
I needed all of these settings to get all my files properly associated. I'm sure you're already aware, but maybe it will help somebody else 

`    "files.associations": {
        "**/playbooks/*.yml": "ansible",
        "**/playbooks/*.yaml": "ansible",
        "**/hostvars/*.yml",
        "**/group_vars/*.yml",
        "**/tasks/*.yaml": "ansible",
        "**/tasks/*.yml": "ansible",
        "**/defaults/*.yaml": "ansible",
        "**/defaults/*.yml": "ansible",
        "**/vars/*.yaml": "ansible",
        "**/vars/*.yml": "ansible",
        "**/meta/*.yaml": "ansible",
        "**/meta/*.yml": "ansible",
        "**/handlers/*.yaml": "ansible",
        "**/handlers/*.yml": "ansible"
    },`

**Comment by mconigliaro** [comment]
The solutions above won't work with [roles](https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-directory-structure), because playbooks exist at the root level too. That means the only globs that will actually work in all cases are `*.yml` and `*.yaml`, which is why I'd argue that the **real** solution is for Ansible to have its own file extension. I doubt anyone here can do anything about that though.
