### ISSUE TITLE
Add inline tagging to ignore linting errors

### ISSUE THREAD

**Issue by sandinak** [ansible/vscode-ansible#167]
### Problem

```
- name: Select authselect profile
  shell: authselect select 
    custom/{{hardening_profile.winbind_profile_name}} 
    with-krb5 
    --force with-faillock without-nullok
```
Gives an error condition "Use Shell only when Shell is required" .. which in this case it is .. so i'd like to be able to annotate the entry so that the plugin will ignore 

### Solution

The python plugin supports the #noqu as an example for skipping formatting.  Alternatively, perhaps parse the yaml and check for args: warn=no and honor that as the understanding that the author means to do this. 
ex:
```
    - name: Create {{ _profile_name }} authselect profile 
      shell: authselect create-profile {{ _profile_name }} -b winbind --symlink-meta
      args: 
        warn: no
```

**Comment by ganeshrn** [comment]
Hey- Thanks for this. The code base is currently going through a major refactoring effort. We don't expect this to be an issue when that work is done. This will remain open until sometime after the new version is released. Please check back in the next month or so.

**Comment by juanvalino** [comment]
:+1:

**Comment by ssbarnea** [comment]
This request has nothing to do with this extension and is aimed at ansible-lint, which already supports `noqa` comments.
