### ISSUE TITLE
Missing Logic for Handling Older Creator Versions in Collection Scaffolding

### ISSUE THREAD

**Issue by abhikdps** [ansible/vscode-ansible#1722]
### Summary

The `ansible-creator` version `24.4.1` does not properly scaffold a collection project from the VS Code Webview due to missing logic to handle older versions of ansible-creator in VSCode extension. While the playbook project creation includes a check for the minimum required creator version, this functionality is absent in collection project scaffolding, leading to errors when using outdated versions of the tool.

### Extension version

24.12.1

### VS Code version

1.95.3

### Ansible Version

```shell
➜  ~ ansible --version
ansible [core 2.17.5]
  config file = None
  configured module search path = ['/Users/abanand/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/abanand/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] (/opt/homebrew/opt/python@3.13/bin/python3.13)
  jinja version = 3.1.4
  libyaml = True
```

### OS / Environment

macOS 15.1.1
Ansible extension version 24.12.1
ansible-creator - 24.4.1
ansible-lint - 24.10.0

### Relevant log output

```shell
------------------------------------ ansible-creator logs ------------------------------------
Command failed: ansible-creator init collection testorg.testcoll /tmp/test --no-ansi -vvv 
usage: ansible-creator [-h] [--version] {init} ...
```

**Comment by alisonlhart** [comment]
Assigning myself to this. This should be a quick bug to fix.
