### ISSUE TITLE
Jinja syntax highlight

### ISSUE THREAD

**Issue by swisspark** [ansible/vscode-ansible#188]
### Problem

It's hard to read Jinja language and complex expressions inside the playbook

### Solution

There was a extension with modifications to support :
- Jinja language
- Jinja expressions for ansible conditions (when, changed_when, failed_when, check_mode)

https://github.com/haad/vs-language-ansible

But it was discontinued, would be awesome if you have that enhancement on yours extension.

### Additional context

You can tell the difference looking at the yaml code below using the [ansible-advanced](https://github.com/haad/vs-language-ansible) and the current extension

```yaml
date_range: |-
    {%- set date_range = [] -%}
    {%- set epoch_timestamp = lookup('pipe', 'date +"%s"') -%}
    {%- for item in range(retention | int, 1) -%}
    {%- set ignored = date_range.append('%Y.%m.%d' | strftime(epoch_timestamp | int + 86400 * item)) -%}
    {%- endfor -%}
    {{ date_range }}
when: hostvars[inventory_hostname].os in platform_supported
```

**Comment by webknjaz** [comment]
I think it's a great idea and I think we'd be happy to review a PR if somebody sends one. Note that there's a good chance that such a contribution belongs in the ansible-language-server repository and not this one.

**Comment by ssbarnea** [comment]
@priyamsahoo @ganeshrn I checked this and our languageTM does recognize `{{...}}` blocks but not the `{%...%}` and `{# ... #}` ones, so it should not be too hard to also recognize these.

Sadly, I am clueless regarding the syntax used to define these. Does any of you know how to patch them?

**Comment by ssbarnea** [comment]
This was fixed in current versions of the extension.
