### ISSUE TITLE
Can't Tab to any tasks

### ISSUE THREAD

**Issue by kynh-2344** [ansible/vscode-ansible#194]
### Summary

When I start creating a task, syntax highlighting and detection works but it can't detect a tab to match YAML style syntax so I have to use many spaces just to make the red curly line under the code disappear, I know the the extension is only in preview status but I really love for this issue to be fixed

### Extension version

v0.4.5

### VS Code version

1.60.1 83bd43bc519d15e50c4272c6cf5c1479df196a4d x64

### Ansible Version

```shell
ansible [core 2.11.5] 
  config file = /home/deploy/project/ansible.cfg
  configured module search path = ['/home/deploy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/deploy/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

<b>OS</b>: Arch Linux
<b>Kernel</b>: 5.14.3-arch1-1
<b>ansible-lint</b>: ansible-lint 5.1.3 using ansible 2.11.5

VS Code I built from an aur package

**Comment by kynh-2344** [comment]
Okay I figured out, I just need to edit the ```settings.json``` with this block

```json
    "[ansible]" :{
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "editor.autoIndent": "keep",
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": true
        }
    },
```
I'm closing this issue now

**Comment by ssbarnea** [comment]
@kynh-2344 Probably you observed that we fixed this in newer versions so you would not need to customize settings anymore, the defaults a just fine.

If everything is fine, please consider writing a small review on https://marketplace.visualstudio.com/items?itemName=redhat.ansible&ssr=false#review-details
