### ISSUE TITLE
Default indentation when writing tasks should be at task level and not at tasks level

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#209]
As seen in screenshot below when writing playbooks, after you type the first key inside a task dictionary the prompt goes to the `tasks:` level as you would have wanted to include a new list entry instead of introducing an extra key to the same task.

![](https://sbarnea.com/ss/Screen-Shot-2021-10-02-11-25-21.48.png)

Ideally we should default to writing a new key inside the same dictionary so users would not be forced to press tab first.

**Comment by webknjaz** [comment]
I would also avoid making the unnecessary indent.

**Comment by tomaciazek** [comment]
> I would also avoid making the unnecessary indent.

The indent is not unnecessary: unindented lists hurt legibility, particularly with constructs like `block`/`rescue`. Just because you can omit that indentation level, doesn't mean you should.
