### ISSUE TITLE
Add option to ignore "undefined variable" error from ansible-lint

### ISSUE THREAD

**Issue by jrglynn2** [ansible/vscode-ansible#222]
### Problem

In VS Code, ansible-lint always pops/highlights an error for undefined variables in playbooks - which I guess I understand if you are using the full ansible-lint package/process.

But here in an editor, where the benefit of ansible-lint is to help you keep your code clean while you are creating/editing, it shouldn't matter. For example, my `hosts:` line will always have an undefined variable, because when running the playbooks, I will feed that information.

### Solution

I would like a setting within VS Code (I presume in the ansible extension) that allows us to "Ignore undefined variable errors" if we want, so that they don't appear.

### Alternatives

I couldn't think of any alternatives, because I see the need for this in the full ansible-lint process/package. Plus, I can't block that rule, because it is the `syntax-check` rule, which you can't disable. And I wouldn't want to - the other pieces of that rule are necessary.

But, in an editor, I will always have undefined variables, so I would want to ignore those errors.

**Comment by jrglynn2** [comment]
@cidrblock agreed that could work, but as @scorpio2k2 points out, that requires changes to every playbook.

I am suggesting a built-in setting that allows us to "Ignore undefined variable errors" if we want.

**Comment by cidrblock** [comment]
BTW. I'm not suggesting I know the answer or it's easy to solve, but I do think if it can be done, it will be in the ansible-lint configuration and not anything vscode specific.... :)

**Comment by scorpio2k2** [comment]
@cidrblock this is a syntax-check problem. Ansible-lint can ignore the hosts issue with this: 

`extra_vars:
     servers: all
`

**Comment by scorpio2k2** [comment]
Same playbook:

ansible-lint playbook.yml                                                                             
WARNING: PATH altered to include /opt/homebrew/Cellar/ansible-lint/6.1.0/libexec/bin
WARNING  Loading custom .yamllint config file, this extends our internal yamllint config.

ansible-playbook playbook.yml --syntax-check
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'servers' is undefined

**Comment by ssbarnea** [comment]
That is outside the scope of the extension, use ansible-lint config to change settings.

**Comment by jrglynn2** [comment]
How do I configure this in ansible-lint config?

**Comment by scorpio2k2** [comment]
--syntax-check has nothing to do with ansible-lint...
