### ISSUE TITLE
Auto Completion didn't work.

### ISSUE THREAD

**Issue by ZaSiMiSaZ** [ansible/vscode-ansible#226]
### Summary

Auto Completion didn't work.

### Extension version

v0.4.5

### VS Code version

Version: 1.61.0 (Universal)

### Ansible Version

```shell
ansible [core 2.11.5] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/think/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/think/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:37:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 2.11.3
  libyaml = True
```

### OS / Environment

macOS: BigSur 11.6

**Comment by Nikitoz78** [comment]
I will support @ZaSiMiSaZ auto Completion didn't work
VS Code version 1.61.2
Extension version v0.4.5
macOS: BigSur 11.6
ansible [core 2.11.6]
  config file = None
  configured module search path = ['/Users/dnikitin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.7.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/dnikitin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Oct 13 2021, 06:45:31) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
