### ISSUE TITLE
Hover docs and autocompletion missing for modules not in ansible.builtin.*

### ISSUE THREAD

**Issue by pgustafs** [ansible/vscode-ansible#264]
### Summary

Smart autocompletion and documentation on hover works as expected on ansible.builtin modules but if I hover on a module belonging to community.general collection for example I get: 

ENOENT: no such file or directory, lstat

and in the Ansible Server log I can see:

ERROR:Response handler 'textDocument/hover' failed with message: Cannot read property 'remove' of undefined

Smart autocompletion only suggest ansible.builtin.* modules, trying with a module in the community.general collection I can see the following in the Ansible Server log:

ERROR:Response handler 'completionItem/resolve' failed with message: Cannot read property 'remove' of undefined

Above worked with version 0.4.5  

 

### Extension version

0.5.1

### VS Code version

Che-Theia 7.36.2

### Ansible Version

```shell
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.venv/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.venv/bin/ansible
  python version = 3.8.6 (default, Jan 22 2021, 11:41:28) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.2
  libyaml = True
```

### OS / Environment

RHEL8.4 UBI
$ python --version
Python 3.8.6
$ ansible-lint --version
ansible-lint 5.2.1 using ansible 2.11.6

### Relevant log output

```shell
ERROR:Response handler 'textDocument/hover' failed with message: Cannot read property 'remove' of undefined
ERROR:Response handler 'textDocument/hover' failed with message: Cannot read property 'remove' of undefined
ERROR:Response handler 'completionItem/resolve' failed with message: Cannot read property 'remove' of undefined
```

**Comment by hille721** [comment]
I have exactly the same issue, no autocompletion and hover docs for non anible.builtin modules, even the syntax highlighting is different:

![image](https://user-images.githubusercontent.com/38468371/144851634-900e79f6-2e95-4b65-8634-3d669bd12a4e.png)


### Extension version
0.7.1

### VSCode version
1.62.3

### Ansible version
````
ansible [core 2.12.0]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/XXX', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /XXX
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, Aug 18 2020, 08:56:04) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
  jinja version = 3.0.3
  libyaml = True

**Comment by ganeshrn** [comment]
Can you please update the extension to latest version and check if the issue is reproduced?

**Comment by priyamsahoo** [comment]
Hi!
Thanks very much for your review. It sincerely means a lot to us
to have an active community that is willing to submit feedback so that we may continue to make the Ansible extension better.

For any user-related queries, you can reach out to us at https://github.com/ansible/community/wiki/Ansible-developer-tools#contact. We do have a great Ansible Developer tools community over there. If you think there is a bug in the extension please raise an issue at https://github.com/ansible/vscode-ansible

**Comment by aradalvand** [comment]
Same issue, what was the resolution here?
