### ISSUE TITLE
Unexpected scalar at node end

### ISSUE THREAD

**Issue by kirkwhetton** [ansible/vscode-ansible#269]
### Summary

When I create an Ansible inventory file in VSCode with this extension enabled, it marks the first host in red and gives the above error message.

### Extension version

1.0

### VS Code version

1.61.2

### Ansible Version

```shell
Using Ansible Tower.
```

### OS / Environment

Windows 10 Enterprise 1909

**Comment by kirkwhetton** [comment]
No response, closing.

**Comment by webknjaz** [comment]
We have weekly triage calls where we try to access the new issues (as many as we can) across like 5 projects. Sorry, we couldn't get to this one soon enough, the backlog is quite big. If we still have this problem, make sure to open a new issue with as many details as you can and wait until it gets triaged.
