### ISSUE TITLE
Vault command not found

### ISSUE THREAD

**Issue by joveice** [ansible/vscode-ansible#289]
### Summary

Trying to encrypt/decrypt with the vault command:
![image](https://user-images.githubusercontent.com/14098624/139586480-688de23c-a457-4f80-9ec5-f75effbd5c40.png)

### Extension version

0.6.0

### VS Code version

1.61.1

### Ansible Version

```shell
$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jove/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]

$ ansible-vault --version
ansible-vault 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jove/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible-vault
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

### OS / Environment

Fedora 34

Settings.json with or without:
`"ansible.vault.executablePath": "/usr/bin/ansible-vault",`

**Comment by ma-fall** [comment]
I'm facing the same issue. 

Extension version: 0.6.0
VS Code version: 1.61.2
OS: Ubuntu 20.04.3 LTS @ WSL2 > using VSCode WSL Remote Extension @ Win10

But I found a way how to get the command running.

After starting VSCode I trigger a "Run Playbook" command:
![image](https://user-images.githubusercontent.com/91664934/139822652-96d92927-f3bc-4ff8-a2d8-287bf0e5822b.png)
Afterwards the encrypt/decrypt command works like a charm. I have to do this every time after starting VSCode.
I hope this somehow helps to find the root cause.

**Comment by jtognazzi** [comment]
On MacOS (M1), the workaround is also working
VS Code Version: 1.61.2
Extension: v0.6.0

ansible 2.9.18
  config file = /Users/xxx/Documents/ansible-deployment/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.9/site-packages/ansible
  executable location = /opt/homebrew/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 04:31:11) [Clang 12.0.5 (clang-1205.0.22.9)]

**Comment by jeinwag** [comment]
I can reproduce the issue and the workaround, will have a look later.

**Comment by joveice** [comment]
At first this didn't solve my issue. But after making sure Ansible was the language of the file as @ssbarnea mentioned here https://github.com/ansible/vscode-ansible/issues/293#issuecomment-963062181
The encrypt works.
So if you still experience this, make sure you have the language of the file as Ansible!
