### ISSUE TITLE
postgresql_user parameter role_attr_flags is not validated correctly

### ISSUE THREAD

**Issue by Oloryn** [ansible/vscode-ansible#292]
### Summary

Any valid values for the postgresql_user parameter role_attr_flags generates the the problem result 

`Value is not accepted. Valid values: "[NO]SUPERUSER", "[NO]CREATEROLE", "[NO]CREATEDB", "[NO]INHERIT", "[NO]LOGIN", "[NO]REPLICATION", "[NO]BYPASSRLS".`

Without digging into the vscode-ansible code (I'm really not much of a javascript programmer),it appears part of the problem is that the definition of role_attr_flags in the json-schema file "Ansible Role" (presuming it was taken from the JSON Schema Store) is: 

`                    "role_attr_flags": {
                        "type": "string",
                        "description": "PostgreSQL user attributes string in the format: CREATEDB,CREATEROLE,SUPERUSER.\nNote that '[NO]CREATEUSER' is deprecated.\nTo create a simple role for using it like a group, use C(NOLOGIN) flag.",
                        "enum": [
                          "[NO]SUPERUSER",
                          "[NO]CREATEROLE",
                          "[NO]CREATEDB",
                          "[NO]INHERIT",
                          "[NO]LOGIN",
                          "[NO]REPLICATION",
                          "[NO]BYPASSRLS"
                        ]
                    },`

I see two problems with this:

1.  While the notation "{NO]<command>" may be obvious to someone versed in PostgreSQL, it's not going to be obvious to an automated code validator.  The enum should probably be something more like
`"enum" [
  "SUPERUSER",
  "NOSUPERUSER",
  "CREATEROLE',
  "NOCREATEROLE",
  etc...
]`

2.  It's actually valid to have multiple of these elements, separated by commas.  I'm not sure if this is something that can be indicated by the json-schema format,, or if it would be something that should be handled by specific coding.

I have in fact verified that no problem result comes up if you specify e.g.

`role_attr_flags: "[NO]CREATEROLE"

which is, of course, not actually a valid value for role_attr_flags, but it demonstrates what is going on with the validation.  Specifying multiple flags, even with the [NO] prefix, still brings up the problem result, demonstrating that checks for multiple flags are not being made.

There's also the issue that this is invoked only when the postgresql_user module is invoked, not when the fully-qualified community.general.postgresql_user name is used.  I suspect that the lack of full-qualified module names in the json-schema file 'Ansible 2.9" accounts for that (the name makes it fairly obvious why).

I fully expect figuring out who's responsible for various parts of this problem will be fun, especially  given the json-schema file published on the JSON Schema Store appears to be generated by https://github.com/shaded-enmity/ansible-schema-generator (which has an issue requesting handling of FQCN's which it appears nothing has been done about).  Given that ansible-schema-generator generates from Ansible module documentation, getting the postgresql_user maintainers to change the documentation for role_attr_flags might be needed.

But this extension is where the problem actually manifests.

### Extension version

v0.6.0

### VS Code version

1.61.2

### Ansible Version

```shell
$ ansible --version
ansible [core 2.11.6] 
  config file = /home/bcoleman/ansible/ansible.cfg
  configured module search path = ['/home/bcoleman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bcoleman/ansible/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/bcoleman/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/bcoleman/ansible/.venv/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True
```

### OS / Environment

Windows 10, WSL (Ubuntu 20.04), ansible-lint 2.11.6

**Comment by ssbarnea** [comment]
Since 0.5.0 we no longer use JSON schemas for tasks/playbooks as it is practically impossible to build a working schema for ansible. You would need a supercomputer to be able to validate it (not joking here). We still use schemas for other file types, but when schemas are involved you will set that the language of the document is `YAML` and not `Ansible`, that how you can identify which language server is used on a particular document (check statusbar).

Are you sure you are using the extension with `ee` disabled? If you have `ee` enabled the local version of Ansible would be irrelevant for its behavior.

We fully rely on documentation of modules to provide validation so if module docs is wrong, we will not be able to validate the data.

@relrod @priyamsahoo Do you happen to know more about this subject?

**Comment by ssbarnea** [comment]
Indeed the `[NO]` notation is mostly a human way of declaring a substring as being optional. I wonder in how many places this is used. Should we just make PR to https://github.com/ansible-collections/community.postgresql to expand these or add extra code to expand this when we load the docs?

If we add code we risk adding bug if some modules may genuinely accept arguments with `[...]` inside them. Maybe we need to grep all the community docs to see to what extent people are using these and if there are any cases where this feature will introduce a new bug.

**Comment by gundalow** [comment]
I spoke with @andersson007 and he says this is fairly a old bit of code, and we should likely replace it.
I'm not aware of any modules apart from community.postgresql using this notation.

Tracked as https://github.com/ansible-collections/community.postgresql/issues/161

Should this vscode-ansible issue be closed?

**Comment by ssbarnea** [comment]
I will close myself once I perform an audit on all community modules. I would be surprised for this to be the only ever occurrence of this. I often use the same notation myself when documenting cli args for example.

**Comment by gundalow** [comment]
> I will close myself once I perform an audit on all community modules. I would be surprised for this to be the only ever occurrence of this. I often use the same notation myself when documenting cli args for example.

Looks like `ansible-test sanity` already checks this via the `validate-modules:doc-choices-do-not-match-spec` check.

So looking for instances of `validate-modules:doc-choices-do-not-match-spec` in `tests/sanity/ignore*.txt` across all collections should be a fairly good indicator.

**Comment by Oloryn** [comment]
Glad you got the issue posted in community.postgresql.  I was looking at that last night, but didn't get it done.

The other aspect of this is that role_attr_flags is essentially a list expressed as comma-delimited elements in a string.  Is that going to be an issue for vscode-ansible to handle, or would it make more sense for it to be an actual list (which requires changing not only community.postgresql doc, but also code, and presents backwards-compatibiliy issues)?    I'll comment this over on the community.postgresql issue, too.

**Comment by ssbarnea** [comment]
I performed a manual audit and apparently that is the only case of a module that used that issue. There are several cases where inside docstrings (not arg spec itself) this shorthand is used, but these are never parsed by a machine.

I will close this bug as we will not do anything about it inside extension. Next version of community posgresql collection will include a fix as that was already merged.

**Comment by gundalow** [comment]
> I performed a manual audit and apparently that is the only case of a module that used that issue. There are several cases where inside docstrings (not arg spec itself) this shorthand is used, but these are never parsed by a machine.


@ssbarnea Thank you for doing this audit. `ansible-test` will ensure no _new_ instances of bad DOCUMENTATION are added, though it's great to know we don't have any other _existing_ problems.
