### ISSUE TITLE
Syntax Highlight Not Work

### ISSUE THREAD

**Issue by ZaSiMiSaZ** [ansible/vscode-ansible#293]
### Summary

 I use extension One Dark Pro but ansible syntax highlight not work on my MacBook.
<img width="824" alt="Screen Shot 2564-11-03 at 12 08 25" src="https://user-images.githubusercontent.com/49062077/140012408-40643108-5308-406a-b40b-c6555bf21c55.png">

### Extension version

ansible v0.6.0

### VS Code version

Version: 1.61.2 (Universal)

### Ansible Version

```shell
ansible [core 2.11.6] 
  config file = None
  configured module search path = ['/Users/ps20354/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.7.0_1/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ps20354/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.0 (default, Oct 13 2021, 06:45:00) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 3.0.2
  libyaml = True
```

### OS / Environment

macOS Monterey 12.0.1

**Comment by joveice** [comment]
Same, Fedora 34
```

Extension version 0.6.0
VS Code version 1.61.1
Ansible Version

$ ansible --version
ansible 2.9.25
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jove/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Aug 30 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
```

**Comment by ssbarnea** [comment]
This bug report is at least incomplete. I installed the mentioned theme and I am unable to reproduce the problem. I do see highlights for module names with it.

I am afraid that the problem has nothing to do with the theme and may be related to other problems.  Your screenshot does not include the full window and I am unable to see if the current language is Ansible.

![](https://sbarnea.com/ss/Screen-Shot-2021-11-04-11-16-59.09.png)

Please try to use Extension Bisect to narrow the issue down.

**Comment by ZaSiMiSaZ** [comment]
Hi ssbarnea, Thanks for you response.  i show you to my screen for extension and full path for ansible file.
<img width="1025" alt="Screen Shot 2564-11-08 at 15 48 46" src="https://user-images.githubusercontent.com/49062077/140711909-f6724226-a4c7-4ef3-beab-0ec7a27948ab.png">
<img width="1070" alt="Screen Shot 2564-11-08 at 15 51 26" src="https://user-images.githubusercontent.com/49062077/140711920-f8ecbe0c-918d-4837-b398-0e36a7b0052a.png">

**Comment by ssbarnea** [comment]
These screenshots do not include the statusbar, look below for statusbar example:
![](https://sbarnea.com/ss/Screen-Shot-2021-11-08-11-30-03.22.png)

That like is critical as it does display the language of current document. In my example you can see "Ansible". If you do not see it on your editor and see something else, like"YAML", you are not using our extension for that particular document.

**Comment by joveice** [comment]
> These screenshots do not include the statusbar, look below for statusbar example: ![](https://camo.githubusercontent.com/bffaf92e30ef47913c4b7df3aea17f0bae9fcf63de87c9665efbdd7f12be7101/68747470733a2f2f736261726e65612e636f6d2f73732f53637265656e2d53686f742d323032312d31312d30382d31312d33302d30332e32322e706e67)
> 
> That like is critical as it does display the language of current document. In my example you can see "Ansible". If you do not see it on your editor and see something else, like"YAML", you are not using our extension for that particular document.

Solved my problem

**Comment by ZaSiMiSaZ** [comment]
Many thanks ssbarnea. solved my problem

**Comment by ssbarnea** [comment]
@ZaSiMiSaZ If everything is fine, maybe you could spare a minute to [review extension on marketplace](https://marketplace.visualstudio.com/items?itemName=redhat.ansible&ssr=false#review-details). As our extension is new, reviews are very important.

**Comment by C0rn3j** [comment]
> If you do not see it on your editor and see something else, like"YAML", you are not using our extension for that particular document.

I had this broke (few weeks ago) and now my .yaml and .yml documents are prioritized to the YAML extension, not the Ansible one, what gives and shouldn't Ansible take priority?

This is my entire settings.json

```json
"git.confirmSync": false,
"editor.renderWhitespace": "boundary",
"window.zoomLevel": -1,
"git.autofetch": true,
"editor.detectIndentation": false,
"editor.tabSize": 2,
"editor.insertSpaces": false,
"explorer.confirmDelete": false,
"files.trimTrailingWhitespace": true,
"files.trimFinalNewlines": true,
"files.insertFinalNewline": true,
"diffEditor.ignoreTrimWhitespace": false,
"redhat.telemetry.enabled": false
```

And this VSC version(extension 0.7.0) - 

```yaml
Version: 1.62.0
Commit: b3318bc0524af3d74034b8bb8a64df0ccf35549a
Date: 2021-11-07T19:37:13.664Z
Electron: 13.6.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.15.2-arch1-1
```
