### ISSUE TITLE
Add setting to allow auto-completion and diagnostics for playbook adjacent collections

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#324]
### Problem

Ansible plugin developers prefer to have collection adjacent to playbook while developing plugins, currently playbook adjacent collections are not supported for auto-completion and diagnostics. 

### Solution

Add boolean setting to allow auto-completion and diagnostics for playbook adjacent collections with default set to `false`

**Comment by priyamsahoo** [comment]
Updated issue: https://github.com/ansible/vscode-ansible/issues/631
