### ISSUE TITLE
 Limit use of settings.json vs UI text box/dropdown

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#327]
### Problem

Currently number of ansible config requires editing the settings.json file and can't be set through vscode preference settings.
<img width="1003" alt="Screen Shot 2021-11-18 at 9 36 52 AM" src="https://user-images.githubusercontent.com/5292461/142350025-b85d8404-b464-4c0c-9607-0d7e7072aaa6.png">

 

### Solution

Edit settings option in extension to be allow editing from UI

**Comment by ssbarnea** [comment]
I am happy to inform you that this ticket is no longer valid, it was already fixed on master branch. I had 2-3 changes related to this and now we have less configurable options and none of them will show `settings.json` link, which is usually the sign of a poorly defined configurable option (there are some exceptions).
