### ISSUE TITLE
Cross project testing for vscode-extension and ansible-language-server

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#329]
### Problem

Update CI jobs to allow cross project testing between vscode-extension and ansible-language-server

### Solution

Update CI jobs to allow cross project testing between vscode-extension and ansible-language-server

**Comment by priyamsahoo** [comment]
It is implemented both ways. The PRs are
- [ansible-language-server] https://github.com/ansible/ansible-language-server/pull/97
- [vscode-ansible] https://github.com/ansible/vscode-ansible/pull/321
