### ISSUE TITLE
Add params to "Run playbook via ansible-playbook"

### ISSUE THREAD

**Issue by JeromeK13** [ansible/vscode-ansible#363]
### Problem

Currently i don't see any documentation or way to set flags for the ansible-playbook command. Which results that u can only run the file on localhost

### Solution

Add option to set falgs like i saw in a old extension within settings.json

something like:
`ansible.ansibelplaybook.custom: "-i ..." `
etc

**Comment by webknjaz** [comment]
This seems to be not hard to implement. A PR is welcome.

**Comment by JeromeK13** [comment]
Alright, I will have a look if I can provide something

**Comment by priyamsahoo** [comment]
Duplicate of #1042. PR is welcome.
