### ISSUE TITLE
ANSIBLE_FORCE_COLOR can prevent extension from working correctly

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#373]
After a debugging session with @priyamsahoo we found what is preventing our extension from working correctly for some users. 

If you happen to have `ANSIBLE_FORCE_COLOR=1` inside shell environment, user ansible.cfg or project specific config, it will break our extension, likely because we try to parse the output as JSON in one or more places without explicitly disabling the coloring on those commands.

Our extension should work regardless how user configured that variable, or others.

**Comment by priyamsahoo** [comment]
The appropriate code to set and unset the values should go into the `ansible-language-server` code base.
