### ISSUE TITLE
Toggling Line Comments does not work with 0.8.0

### ISSUE THREAD

**Issue by morafe** [ansible/vscode-ansible#451]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

With version 0.8.0 of the redhat.ansible extension the Toggle Line Comment functionality does not work.  
Both the keyboard shortcut (command + /) or selecting the "Toggle Line Comment" option from the menu bar do not work and don't do anything.  

Changing the language setting to YAML, the feature works again. Changing the language setting back to Ansible, the feature stops working.

Installing an older version of the extension (version 0.7.1), the feature to works with no problem.

### Extension version

0.8.0

### VS Code version

1.65.0

### Ansible Version

```shell
ansible 2.9.20
  config file = None
  configured module search path = ['/Users/echiu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/echiu/.pyenv/versions/3.8.10/envs/ansible2.9-3.8/lib/python3.8/site-packages/ansible
  executable location = /Users/echiu/.pyenv/versions/ansible2.9-3.8/bin/ansible
  python version = 3.8.10 (default, Jul  1 2021, 16:18:32) [Clang 11.0.3 (clang-1103.0.32.29)]
```

### OS / Environment

macOS Monterey version 12.1, ansible-lint 5.1.2 using ansible 2.9.20

**Comment by ssbarnea** [comment]
Fixed in 0.8.1, get it from Fixed in 0.8.1 https://marketplace.visualstudio.com/items?itemName=redhat.ansible
