### ISSUE TITLE
Auto closing brackets/quotes not working

### ISSUE THREAD

**Issue by camileck** [ansible/vscode-ansible#453]
### Sanity check

- [x] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

EDIT: Works just fine with 0.7.1 version

Hello team, 

Great work with the extension! I have one problem though. Auto closing brackets/quotes  that is featured at Marketplace extension page does not work for me. Steps to reproduce: 
create .yaml file (file language set to Ansible)
type: "{{
and nothing happens. I would expect the brackets and quote to be closed. VS Code itself has a default setting of autoclosing set to: Languagedefined. Tried with this setting set to "always" but with no effect. 

### Extension version

0.8.0

### VS Code version

1.65

### Ansible Version

```shell
ansible 2.9.6
  config file = /home/cut/private_repo/playbooks/centos-update/ansible.cfg
  configured module search path = ['/home/cut/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

### OS / Environment

Windows 10, WSLv2, Ubuntu 20.04, ansible-lint 4.2.0

**Comment by ssbarnea** [comment]
Fixed in 0.8.1 https://marketplace.visualstudio.com/items?itemName=redhat.ansible
