### ISSUE TITLE
Replace `Number.MAX_SAFE_INTEGER` with `integer.MAX_VALUE` in tests

### ISSUE THREAD

**Issue by priyamsahoo** [ansible/vscode-ansible#460]
After the release of the language server which contains this change https://github.com/ansible/ansible-language-server/pull/261, and the release of extension to use the ansible-language-server version 0.5.3, the e2e tests will fail.

To fix them, we need to update every instance of `Number.MAX_SAFE_INTEGER` with `integer.MAX_VALUE (from vscode-languageclient)`.
 
Refer to this PR for details: https://github.com/ansible/ansible-language-server/pull/261

**Comment by ganeshrn** [comment]
Fixed in v0.8.1
