### ISSUE TITLE
notify type in yaml schema should support string AND array

### ISSUE THREAD

**Issue by KMouratidis** [ansible/vscode-ansible#466]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

yaml-schema complains that `notify` should accept a string for this definition:

```
  notify:
    - Restart Docker
    - Restart NFS
```

It seems the definition is:

```
"notify": {
    "title": "Notify",
    "type": "string"
},
```

But (maybe) it should be:

```
"notify": {
    "title": "Notify",
    "anyOf": [
        {
            "type": "string"
        },
        {
            "type": "array"
        }
    ]
},
```

### Extension version

0.8.1

### VS Code version

1.65.2

### Ansible Version

```shell
~$ ansible --version
ansible [core 2.12.3]
  config file = ~/.ansible.cfg
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <env_path>/lib/python3.10/site-packages/ansible
  ansible collection location = ~/.ansible/collections:/usr/share/ansible/collections
  executable location = <env_path>/bin/ansible
  python version = 3.10.3 (main, Mar 18 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.3
  libyaml = False
```

### OS / Environment

OS: Fedora 35
Kernel: 5.16.16-200.fc35.x86_64
ansible-lint: 6.0.1
python: 3.10

**Comment by ganeshrn** [comment]
@KMouratidis Please raise an on the schema project https://github.com/ansible-community/schemas/issues
