### ISSUE TITLE
Feature to enable/disable ansible server in docker container

### ISSUE THREAD

**Issue by pertoft** [ansible/vscode-ansible#484]
### Problem

Related to #477 where I had a problem where vscode is not working with ansible. 
The error was due to a misconfiguration, where the ansible server were supposed to run in a docker container.

### Solution

I suggest a feature where an easy way to enable/disable the ansible server in a docker container. Also a better warning when its misconfigured.

**Comment by priyamsahoo** [comment]
This PR: https://github.com/ansible/ansible-language-server/pull/318, will fix the issue.
