### ISSUE TITLE
Command failed: ansible-lint: no such option: --offline

### ISSUE THREAD

**Issue by doxxx** [ansible/vscode-ansible#498]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

When I open an Ansible yml file for the first time in a VSCode window, I get the following error popup:

```
Command failed: ansible-lint  --offline --nocolor -f codeclimate "/home/gtyler/dev/ansible/playbooks/roles/mount-installers/tasks/main.yml"
Usage: ansible-lint [options] [playbook.yml [playbook2 ...]]

ansible-lint: error: no such option: --offline
```

### Extension version

0.9.0

### VS Code version

1.67.1

### Ansible Version

```shell
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/gtyler/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
```

### OS / Environment

Windows 10, WSL Ubuntu 20.04
ansible-lint 4.2.0 (from Ubuntu package)

### Relevant log output

```shell
Path for lint:  /usr/bin/ansible-lint
Validating using ansible-lint
[Info  - 2:12:36 PM] [ansible-lint] Usage: ansible-lint [options] [playbook.yml [playbook2 ...]]

ansible-lint: error: no such option: --offline

Ansible-lint command execution failed. Falling back to ansible syntax-check
Validating using ansible syntax-check
not a playbook...
```

**Comment by priyamsahoo** [comment]
@doxxx, could you please specify the version of ansible-lint installed on your system?

**Comment by doxxx** [comment]
4.2.0 as I wrote in the environment section.

**Comment by priyamsahoo** [comment]
@doxxx, you are using an ancient version of the ansible-lint.
Please update ansible-lint (min supported version is 5.0.0) and the extension work fine again!

**Comment by doxxx** [comment]
It's the most up-to-date version in Ubuntu 20.04.

**Comment by doxxx** [comment]
Uninstalling the ansible-lint from Ubuntu and installing it from pypi results in a bunch of errors because it requires a newer version of ansible-core, which conflicts with the ansible 2.9.6 already installed from Ubuntu repo. When I install ansible-lint v5.0.0 specifically, it installs successfully, but I now get a different error in vscode:

```
Command failed: ansible-lint  --offline --nocolor -f codeclimate "/home/gtyler/dev/ansible/playbooks/roles/algorithms-vnv/tasks/r.yml"
Traceback (most recent call last):
  File "/usr/local/bin/ansible-lint", line 8, in <module>
    sys.exit(_run_cli_entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ansiblelint/__main__.py", line 254, in _run_cli_entrypoint
    sys.exit(main(sys.argv))
  File "/usr/local/lib/python3.8/dist-packages/ansiblelint/__main__.py", line 170, in main
    from ansiblelint.generate_docs import rules_as_rich, rules_as_rst
  File "/usr/local/lib/python3.8/dist-packages/ansiblelint/generate_docs.py", line 6, in <module>
    from rich.console import render_group
ImportError: cannot import name 'render_group' from 'rich.console' (/usr/local/lib/python3.8/dist-packages/rich/console.py)
```

**Comment by ssbarnea** [comment]
Sorry but we do not support older versions. If you have problems with ansible, either use a separated virtualenv or switch to user execution environments for the extension.

In the future we will add a warning when an unsupported or broken version of the linter is detected.
