### ISSUE TITLE
Formatting Extension 'Ansible' is configured as formatter but it cannot format 'Ansible'-files'

### ISSUE THREAD

**Issue by tepene** [ansible/vscode-ansible#505]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

VScode reports that it no longer can format "ansible files". Code auto completion and syntax highlighting is working though.

Error: `Formatting Extension 'Ansible' is configured as formatter but it cannot format 'Ansible'-files'`

### Extension version

0.9.0

### VS Code version

1.67.2

### Ansible Version

```shell
ansible [core 2.12.5]
  config file = /workspaces/netinsight-aci/ansible.cfg
  configured module search path = ['/workspaces/netinsight-aci/library']
  ansible python module location = /home/vscode/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /workspaces/netinsight-aci/collections
  executable location = /home/vscode/.local/bin/ansible
  python version = 3.10.4 (main, Apr  7 2022, 03:15:56) [GCC 10.2.1 20210110]
  jinja version = 3.1.1
  libyaml = True
```

### OS / Environment

Ubuntu 20.04 with VSCode Python devcontainer `ARG VARIANT="3.10-bullseye"`

### Relevant log output

```shell
Path for lint:  /home/vscode/.local/bin/ansible-lint
Validating using ansible-lint
[Info  - 10:14:40 AM] [ansible-lint] WARNING: PATH altered to include /usr/local/bin
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: /workspaces/netinsight-aci/pb_aci_infrastructure-2-netinsight.yml
```

**Comment by ssbarnea** [comment]
This is a bug with vscode itself, as you can see it does list all possible extensions there and most of them have nothing to do with formatting.
