### ISSUE TITLE
Add command decorations for changed and failed Ansible tasks in playbook executions

### ISSUE THREAD

**Issue by mattico** [ansible/vscode-ansible#572]
### Problem

I'll often run a long Ansible playbook and come back to see some tasks have changed or failed. I usually want to check which tasks changed or failed to make sure I know what happened. I then have to scroll through the output looking for the tasks.

### Solution

VS Code supports [command decorations in the terminal's overview ruler / scrollbar](https://code.visualstudio.com/docs/terminal/shell-integration#_command-decorations-and-the-overview-ruler). We could mark changed and failed tasks in the overview ruler so that you can know where to scroll to to find the changed tasks.

There are [some mentions](https://code.visualstudio.com/api/references/vscode-api#OverviewRulerLane) of the overview ruler markers in the extension API but it's not clear to me if this type of feature is completely supported yet.

### Alternatives

An Ansible callback plugin could output a VSCode escape sequence telling it to create the overview ruler marks. It doesn't appear that VSCode has escape sequences flexible enough to do this at the moment.

An Ansible callback plugin could hide non-changed-or-failed tasks in the printed output.

We could have a rich renderer for ansible playbook executions run through the vscode-ansible extension as extension tasks. I'm not sure how or whether this would work.

**Comment by ssbarnea** [comment]
Can you please find us an example of another tool that can produce these without running different subprocesses for each reporting step? If you find such example, we will likely be able to use a custom callback to achieve it.
