### ISSUE TITLE
ansible extension becomes inactive

### ISSUE THREAD

**Issue by braindevices** [ansible/vscode-ansible#576]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

It works fine days ago. Today the ansible extension stops working. No lint, no grammar checking, no completion, nothing works. The Runtime status become `Not yet activated.`. I tried to reinstall the extension. It does not work.

Suspicious change was I upgraded the ansible yesterday

Path to ansible is: `ansible`, Path to `ansible-lint` is : `ansible-lint`.

trace is set to verbose

### Extension version

v0.11.10

### VS Code version

1.69.2

### Ansible Version

```shell
ansible [core 2.13.2]
  config file = /home/user/.ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Ubuntu 20.04

### Relevant log output

```shell
no output at all
```

**Comment by priyamsahoo** [comment]
Please update to v0.11.12 (pre-release). Let us know if it still doesn't work!

**Comment by braindevices** [comment]
v0.11.12 works fine

**Comment by charltonstanley** [comment]
Pre-release `v0.11.12` fixed this for me as well!
