### ISSUE TITLE
Linting and autocomplete, etc have stopped working

### ISSUE THREAD

**Issue by stuartbloom-alvaria** [ansible/vscode-ansible#591]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

Running vs code with the extension has stopped working with lint, etc. I no longer get errors reported or help when pressing ctrl+space or hovering over keywords.

I have also noticed that when saving a file I no longer see ansible-lint working :(

### Extension version

0.11.10

### VS Code version

1.70.1

### Ansible Version

```shell
ansible [core 2.11.6]
  config file = /home/sbloom/code/wfm/ansible/ansible.cfg
  configured module search path = ['/home/sbloom/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sbloom/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/sbloom/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/sbloom/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 2.11.3
  libyaml = True
```

### OS / Environment

windows 10, wsl debian 11, ansible-lint 5.2.1 using ansible 2.11.6

**Comment by ssbarnea** [comment]
Install the pre-release version, it will work.
