### ISSUE TITLE
[RFE] Add support for Ansible extension webview (side-panel)

### ISSUE THREAD

**Issue by ganeshrn** [ansible/vscode-ansible#599]
### Problem

Currently there is no single view to provide all the information related to Ansible within the environment. The Ansible environment information is currently displayed in the bottom right side bar. 
![Screen Shot 2022-08-23 at 6 25 32 PM](https://user-images.githubusercontent.com/5292461/186163888-4effc71c-52a8-4c78-bef1-3ea643af8d3d.png)

The approach is not extendible if we want to add additional features for Ansible and integration with other devtool projects like [Ansible plugin builder](https://github.com/ansible-community/ansible.plugin_builder)

### Solution

The [webview extension API's](https://code.visualstudio.com/api/extension-guides/webview) can be used to create a customised view for Ansible extension.
The webview sections for Ansible to start with can be:

* Ansible Environment Info
* Ansible Execution Environment
* Ansible Plugin Builder
* Ansible Collection Docs
* Ansible Playbooks (will render all the playbook in workspace with option to run it in the view)

**Comment by ssbarnea** [comment]
We also need to show playbooks, roles, collections, integration/unit tests inside the side window. Eg. docker extension

**Comment by priyamsahoo** [comment]
The webview feature has been added to the extension with the integration of ansible-creator (PR #1000)
