### ISSUE TITLE
Support vscode outline

### ISSUE THREAD

**Issue by Igorgro** [ansible/vscode-ansible#601]
### Problem

Currently when opening any ansible file the extension doesn't provide an outline which makes it hard to navigate trough a big document.

### Solution

Implement a [DocumentSymbol](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbol) to provide a more advanced way to navigate through Ansible files using outline and breadcrumbs

**Comment by ICHx** [comment]
![image](https://user-images.githubusercontent.com/11556527/202373348-bfc35fae-132e-4a09-9fbd-0a616680e27e.png)

adding screenshot, YAML outline is supported when VS Code language set to YAML instead of 'Ansible'

**Comment by ICHx** [comment]
but not after doing so
![image](https://user-images.githubusercontent.com/11556527/202373538-5a20e1ce-d7f4-4429-8698-7331c2e16f1b.png)

**Comment by petr-fischer** [comment]
+1

**Comment by clearlybaffled** [comment]
+1

**Comment by eduardo-at** [comment]
+1

**Comment by Igorgro** [comment]
Please, don't post '+1's, it just polluting discussion and doesn't provide anything constructive. Just use 👍🏻

**Comment by priyamsahoo** [comment]
While this seems to be a great addition, currently we are not planning to work on this. Be assured that we will be happy to review a PR for this feature.
