### ISSUE TITLE
Support role/meta directory

### ISSUE THREAD

**Issue by Igorgro** [ansible/vscode-ansible#606]
### Problem

This extension currently does not support autocomplete for `meta/` directory files of the role such as `main.yml` and `argument_specs.yml`. While the support of `main.yml` can be workarounded by switching to YAML extension, which loads the correct YAML schema, there still no way to enable autocomplete for `argument_specs.yml` file.

### Solution

Either provide direct support for this two files in this extension, or collaborate with YAML extension to automatically load correct YAML shema for these files.

**Comment by ssbarnea** [comment]
We already support argument-spec with auto-complete via YAML extension, which is used for these files.
