### ISSUE TITLE
No fallback to syntax-check when ansible-lint shows invalid yaml

### ISSUE THREAD

**Issue by max06** [ansible/vscode-ansible#615]
### Problem

When I'm working on ansible roles in vscode, and I have autosave enabled after a relatively short delay (like 1 second), ansible-lint get's triggered before I'm actually done with my change.

This results in 2 notifications:
![image](https://user-images.githubusercontent.com/7556827/189170450-32388779-a17d-496c-8cbf-761d6b3a708f.png)

The error is about invalid yaml content, which is true - in that moment. 

### Solution

There is no need to fall back to `ansible syntax-check` if a usable ansible-lint is in place. Imo, a fallback should only happen if there's either no ansible-lint, or the installed one can't be used for whatever reason.

Instead of having 2 notifications, I'd prefer to have a more silent message, for example in the status bar telling me about broken yaml.

**Comment by priyamsahoo** [comment]
With the message. I am assuming that ansible-lint is not present in your environment. You can confirm that by hovering over ansible version in the status bar which will give you a clear message.

**Comment by max06** [comment]
I'm sorry to disappoint you, but ansible-lint is present and works.

The error message is caused when the file checked by ansible-lint does not contain valid yaml.

**Comment by priyamsahoo** [comment]
We will definitely look into it, thanks for raising the issue.
But before that, could you share your environment's ansible Metadata (which you can get by hovering over the yellow status bar item) ?

**Comment by max06** [comment]
![image](https://user-images.githubusercontent.com/7556827/189342153-f4d8ea3c-11a6-4ea7-aca1-debd13ff9566.png)

This is a vscode devcontainer. Non-root, no virtualenv. 

`requirements.txt` - stripped. Container simply runs `pip3 install --user -r requirements.txt` after creation.
```text
ansible==4.4.0
Jinja2>=2.11.2
netaddr
PyYAML==5.3.1
molecule
ansible-lint
pycodestyle==2.9.1
pylint
```

The warning in the metadata is not correct, and probably caused by the ansible-lint version output:

```text
 $ ansible-lint --version                                                                                                                                                                                                                              
WARNING: PATH altered to include /usr/local/bin
ansible-lint 5.4.0 using ansible 2.11.12
```

**Comment by priyamsahoo** [comment]
Hi @max06,
This is a little new and needs some investigation. We are looking into it.

Just one more thing, could you try putting the ansible-lint path in the settings once, i.e., in `ansible.ansibleLint.path`? And try diagnostics on the file again after that. Does it still fall back to syntax check, and is the warning still there? 

The issue is that the extension cannot pick up the ansible-lint executable.

**Comment by max06** [comment]
Hey @priyamsahoo, thank you for looking into this!

You're probably right, something doesn't work here. Even after setting the path for ansible-lint, the extension is unable to get the information.

To make debugging easier, I prepared a fully functional devcontainer for you: https://github.com/max06/ansible-lint-debug
In case you've never used devcontainers before: You can clone the repository, open it in vscode with the`ms-vscode-remote.vscode-remote-extensionpack`-extensions installed and confirm the "open in container?"-question. The environment will be ready after 2-3 minutes with ansible 4.4.0, ansible-lint 5.4.0, your extension and the filetype mapping.

I've also added a demo-role `test` with 2 broken tasks. To trigger the warning shown in this issue, remove the comments from the second task and save.

**Comment by max06** [comment]
Hello @priyamsahoo 

A quick update: `v0.14.73` obviously solved the issue of not recognizing the ansible-lint binary.

```jsonc
[Trace - 11:26:16 AM] Received notification 'update/ansible-metadata'.
Params: [
    [
        {
            "ansible information": {
                "ansible version": "Ansible core 2.11.12",
                "ansible location": "/home/vscode/.local/lib/python3.10/site-packages/ansible",
                "config file path": [
                    "None"
                ],
                "ansible collections location": [
                    "/home/vscode/.ansible/collections",
                    "/usr/share/ansible/collections",
                    "",
                    "/usr/local/lib/python310.zip",
                    "/usr/local/lib/python3.10",
                    "/usr/local/lib/python3.10/lib-dynload",
                    "/home/vscode/.local/lib/python3.10/site-packages",
                    "/usr/local/lib/python3.10/site-packages"
                ],
                "ansible module location": [
                    "/home/vscode/.ansible/plugins/modules",
                    "/usr/share/ansible/plugins/modules",
                    "/home/vscode/.local/lib/python3.10/site-packages/ansible/modules"
                ],
                "ansible default host list path": [
                    "/etc/ansible/hosts"
                ]
            },
            "python information": {
                "python version": "Python 3.10.6",
                "python location": "/usr/local/bin/python"
            },
            "ansible-lint information": {
                "ansible-lint version": "ansible-lint 5.4.0 using ansible 2.11.12",
                "ansible-lint location": "/home/vscode/.local/bin/ansible-lint"
            }
        }
    ]
]
```

However it still looks like ansible-lint is not working, at least I get the same results described in the initial post.

**Comment by ganeshrn** [comment]
The problem described in the original post is fixed by PR https://github.com/ansible/vscode-ansible/pull/648 and https://github.com/ansible/ansible-language-server/pull/448

Please update the extension to the latest pre-release version and try it out.

**Comment by max06** [comment]
@ganeshrn I'm sorry, I can't test 😢 

![image](https://user-images.githubusercontent.com/7556827/194551674-e7156942-f575-479d-b10a-30d77acfe759.png)

**Comment by ganeshrn** [comment]
@max06 Can try after upgrading the VSCode version?

**Comment by max06** [comment]
This is the latest version. It's too new for the extension.

**Comment by ganeshrn** [comment]
Sorry I missed that the VSCode version you have is the latest one.

It is working for me with pre-release extension version v0.14.81 and VSCode:
Version: 1.71.2 (Universal)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

We will figure why the extension is not working with latest VSCode release

**Comment by max06** [comment]
Attention: The dependency redhat.vscode-yaml is not compatible. I'd start there....

Please ping me if you need someone for testing 👍🏼

**Comment by ganeshrn** [comment]
Thanks the information is helpful

**Comment by max06** [comment]
@rgrunber Mhm... those dates look odd. Like the prerelease is older than the last stable...

**Comment by rgrunber** [comment]
If I inspect the `extension.vsixmanifest` I see `<Property Id="Microsoft.VisualStudio.Code.PreRelease" Value="true" />` . However, if I manually install it (which succeeds), and look at the `package.json` inside the extension installation folder, I see :

```
"__metadata": {
...
"isPreReleaseVersion": false,
...
}
```

The extension also doesn't get the pre-release decorations. However, I don't know how much of this stems from the fact that it's clearly not being published correctly / the marketplace not handling it correctly.

**Comment by max06** [comment]
@ganeshrn Can you remove the broken prerelease of the `yaml`-extension from the store to keep vscode from using it?

**Comment by rgrunber** [comment]
For vscode-yaml, I think the issue is at https://github.com/redhat-developer/vscode-yaml/blob/main/Jenkinsfile#L48 . This is the only place I see the `--pre-release` flag used, and it only publishes a generic version on platforms that aren't supported, but there's nothing published for the other (supported?) platforms. If vscode-yaml doesn't publish platform-specific code (I think that's the case?), then there's no need for this. You could probably remove `--target win32-ia32 win32-arm64 linux-armhf alpine-x64 alpine-arm64`.

**Comment by max06** [comment]
Hello there!
Sorry for the late reply, I missed the related pull request.
But: I have good news. `v1.0.93` seems to use ansible-lint properly. The message is different and the source mentions `ansible-lint` now instead of `ansible`.

Let's get back to my initial post: The red error telling me ansible-lint failed still appears when there's a yaml syntax error in the file tested. This is correct - the format is invalid. Remove a `:` from one of the files for testing. I still think the error message should be supressed in this case, sinse this is likely to be caused by autosave, when I'm actually not finished.

**Comment by priyamsahoo** [comment]
@max06, could you share a sample playbook so I can replicate this on my local system? This would become easier for me to debug.

**Comment by max06** [comment]
@priyamsahoo absolutely! Have a look at https://github.com/max06/ansible-lint-debug. If you remove the comments in Lines 4 and 5, the yaml is broken enough to show the issue.

**Comment by yaegassy** [comment]
@max06 Try upgrading your version of `ansible-lint` and `ansible`.

I have given the same answer for another issue, but I think the behavior depends on the version of the tool

- <https://github.com/ansible/vscode-ansible/issues/668>

**Comment by max06** [comment]
@yaegassy I think you're right.

```json
[{
	"resource": "/workspaces/redacted/ansible/roles/testing/tasks/main.yml",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "load-failure",
		"target": {
			"$mid": 1,
			"external": "https://ansible-lint.readthedocs.io/rules/load-failure/",
			"path": "/rules/load-failure/",
			"scheme": "https",
			"authority": "ansible-lint.readthedocs.io"
		}
	},
	"severity": 8,
	"message": "Failed to load YAML file",
	"source": "ansible-lint",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2147483648
}]
```

Latest ansible and lint are no longer showing the red error notification. Time to update... yay. 
Thx again!
