### ISSUE TITLE
Remove "certify" checkbox in issue template and replace with kind notice

### ISSUE THREAD

**Issue by cidrblock** [ansible/vscode-ansible#616]
### Sanity check

- [X] I certify that the `redhat.ansible` extension is in use and the language of the document in this bug report shows up as `Ansible`

### Summary

After the most recent file association changes have been released.

### Extension version

N/A

### VS Code version

N/A

### Ansible Version

```shell
N/A
```

### OS / Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by priyamsahoo** [comment]
Completed: https://github.com/ansible/vscode-ansible/pull/640
