### ISSUE TITLE
Add support for VS Code extension "Better Comments"

### ISSUE THREAD

**Issue by MallocArray** [ansible/vscode-ansible#665]
### Problem

Better Comments extension allows for special coloring of different comment types.  
https://marketplace.visualstudio.com/items?itemName=aaron-bond.better-comments

Recent updates to this extension needs language support for it to work.  Today it works as expected when the VSCode language is set to YAML but when switched to Ansible, the extra coloring no longer functions.

### Solution

The author mentioned in an issue comment that they have to work with different extension creators to add support
https://github.com/aaron-bond/better-comments/issues/418#issuecomment-1183568489

It would be great if this could be added to the Ansible extension, so I can still see the benefits of Better Comments when a file is set to the Ansible language.

### Alternatives

I've opened a request on the Better Extension side, but though to ask from the Ansible extension side as well
https://github.com/aaron-bond/better-comments/issues/434

**Comment by ssbarnea** [comment]
While I never used that extension myself, I would not mind for us to make adjustments to keep it working. We will clearly be happy to look at a pull request.

By looking at the extension, I could see one use-case where we might want to color bit different the "noqa" comments that tell ansible-lint to ignore some validations.
