### ISSUE TITLE
Virtualenv / python settings are ignored

### ISSUE THREAD

**Issue by ppuschmann** [ansible/vscode-ansible#666]
### Summary

On my macOS I'm trying to keep things tidy.
That is the reason why I installed virtualenv and virtualenvwrapper. 
Python is installed via brew.

There is some configuration in VSCode to select Python's virtualenv in the settings.json:
```
"python.venvFolders": [
        "~/.virtualenvs"
    ],
```

This works perfectly fine and the information (Python-version & selected virtualenv) is shown in the statusbar,
**but only** if there's some different filetype than Ansible is selected 
or the Ansible-extension is uninstalled or disabled.

With active Ansible-extension  the virtualenv-Configuration is completely ignored and I get (of course) errors like these:

> Ansible-lint is not available. Kindly check the path or disable validation using ansible-lint

This is my statusbar with any other file **but** "Ansible":
![vscode-settings-file](https://user-images.githubusercontent.com/3431761/196747366-fc12cd91-2762-4e0a-bed5-bbde2eff0304.png)

This is my statusbar with a file of the type "Ansible":
![ansible-file](https://user-images.githubusercontent.com/3431761/196747400-7fcae380-6859-4af8-8bd9-dbf5e8e90a22.png)

Additionally / of course **none** of the other interesting features of the Extension "Ansible" is working:
* autocompletion does not work
* linting does not work

### Extension version

v1.0.90

### VS Code version

1.72.2

### Ansible Version

```shell
ansible --version    
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/Users/ppu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ppu/.virtualenvs/ansible-runner/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/ppu/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/ppu/.virtualenvs/ansible-runner/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS 12.6, M1
ansible-lint --version        
ansible-lint 6.8.2 using ansible 2.13.5

**Comment by ppuschmann** [comment]
The error-messages about `ansible-lint not found` started with version `v0.14.71`.

**Comment by ppuschmann** [comment]
So I'm now using 
```
    "ansible.python.interpreterPath": "/opt/homebrew/Cellar/python@3.10/3.10.8/bin",
    "ansible.python.activationScript": "~/.virtualenvs/ansible-runner/bin/activate",
    "python.venvFolders": [
        "~/.virtualenvs"
    ],
```
and it works:
![ansible-file-2](https://user-images.githubusercontent.com/3431761/196904821-2aaaf0d0-f2d7-4c9a-8eb9-b5cc86c4dd8d.png)

I still have to say, I don't like it that much, because I now have to use configuration pointing to distinct Python versions in VSCode.

**Comment by robinmalik** [comment]
I'm not sure if this is related but I'm hitting errors today, whenever VS Code opens an Ansible `.yml` file.

Two popups in the lower right, whether using the pre-release version of the extension or not.

```
spawn C:\WINDOWS\system32\cmd.exe ENOENT
Source: Ansible (Extension)

Ansible-lint is not available. Kindly check the path or disable validation using ansible-lint
Source: Ansible (Extension)
```

VS Code:
```
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25217
Sandboxed: No
```

**Comment by ppuschmann** [comment]
@robinmalik I'd guess this issue is different than my initial issue since you're apparently not using virtualenv but using Ansible in some container.

@yaegassy I still think the configuration with virtualenv and Python-Interpreter-Path could be more smooth, but I'd also be fine with closing this issue.

**Comment by rdbisme** [comment]
> So I'm now using
> 
> ```
>     "ansible.python.interpreterPath": "/opt/homebrew/Cellar/python@3.10/3.10.8/bin",
>     "ansible.python.activationScript": "~/.virtualenvs/ansible-runner/bin/activate",
>     "python.venvFolders": [
>         "~/.virtualenvs"
>     ],
> ```
> 
> and it works: ![ansible-file-2](https://user-images.githubusercontent.com/3431761/196904821-2aaaf0d0-f2d7-4c9a-8eb9-b5cc86c4dd8d.png)
> 
> I still have to say, I don't like it that much, because I now have to use configuration pointing to distinct Python versions in VSCode.

I agree. Can't you just use the current activated `virtualenv`, by default? Or just `ansible` commands available in `PATH` by default?

**Comment by priyamsahoo** [comment]
You can directly choose the python environment with a single click now, similar to how to choose it in the python vscode extension.

**Comment by tim-alt-delete** [comment]
I am still having this issue, would greatly appreciate any help.

Ansible cannot find my `.venv` despite it being active in the current window.

<img width="637" height="116" alt="Image" src="https://github.com/user-attachments/assets/d66ec066-bdf5-4825-9f93-ec189d3fc5e1" />

<img width="671" height="94" alt="Image" src="https://github.com/user-attachments/assets/3a47e75f-2bbb-4fff-a3f9-2c0b7ba86992" />

From VSCode terminal
```bash
((.venv) ) [tpulliam@ansible-control-node lab1]$ python --version
Python 3.12.12
((.venv) ) [tpulliam@ansible-control-node lab1]$ which python
~/rhce/lab1/.venv/bin/python
((.venv) ) [tpulliam@ansible-control-node lab1]$ ansible-lint --version
ansible-lint 26.4.0 using ansible-core:2.20.5 ansible-compat:26.3.0 ruamel-yaml:0.19.1 ruamel-yaml-clib:0.2.15
((.venv) ) [tpulliam@ansible-control-node lab1]$ ansible-config --version
ansible-config [core 2.20.5]
  config file = /home/tpulliam/rhce/lab1/ansible.cfg
  configured module search path = ['/home/tpulliam/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tpulliam/rhce/lab1/.venv/lib64/python3.12/site-packages/ansible
  ansible collection location = /home/tpulliam/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/tpulliam/rhce/lab1/.venv/bin/ansible-config
  python version = 3.12.12 (main, Mar 27 2026, 00:00:00) [GCC 14.3.1 20250617 (Red Hat 14.3.1-2)] (/home/tpulliam/rhce/lab1/.venv/bin/python3)
  jinja version = 3.1.6
  pyyaml version = 6.0.3 (with libyaml v0.2.5)
```

## Additional Information

### VSCode Version
Version: 1.117.0 (Universal)
Commit: 10c8e557c8b9f9ed0a87f61f1c9a44bde731c409
Date: 2026-04-21T16:12:14-07:00
Electron: 39.8.7
ElectronBuildId: 13841579
Chromium: 142.0.7444.265
Node.js: 22.22.1
V8: 14.2.231.22-electron.0
OS: Darwin arm64 24.6.0

### Ansible VSCode Extension
Identifier: redhat.ansible
Version: 26.4.4
Last Updated: 46 minutes ago
Size: 22.01MB
