### ISSUE TITLE
Extension does not honor warn_list in .ansible-lint and command-line arguments specified in extension settings

### ISSUE THREAD

**Issue by balaji-dutt** [ansible/vscode-ansible#667]
### Summary

Hi,

I'm finding that the extension does not seem to use any rules added to `warn_list` in `.ansible-lint` and/or command line parameters provided via extension settings as `--warn-list WARN LIST`

Steps to reproduce:
* Add an `.ansible-lint` file at the root of playbooks folder as follows:

~~~
---
# .ansible-lint
use_default_rules: true
skip_list:
  - command-instead-of-shell
warn_list:
  - package-latest
  - no-relative-paths
~~~

* Add the following step to a playbook in the `/playbooks` dir:

~~~
---
- name: Test the vscode extension
  hosts: all
  tasks:
  - name: Copy the CA certificate
    ansible.builtin.copy:
      src: ../../files/certs/ca.crt
      dest: /root/ca.crt
      owner: root
      group: root
      mode: '0644'
    tags:
     - certs

~~~

* Open the `playbook.yml` file in VSCode and the following error appears:
![vscode](https://user-images.githubusercontent.com/3147070/197450595-139872db-5d2d-4978-b6a8-a1ac33529307.png)
  * This error appears even if we modify the extension settings as follows:
    ~~~
    "ansible.validation.lint.arguments": "--warn-list no-relative-paths"
    ~~~

### Extension version

v1.0.90

### VS Code version

Version: 1.72.2 (Universal)

### Ansible Version

```shell
$  ansible --version
ansible [core 2.13.5]
  config file = /Users/balaji/.ansible.cfg
  configured module search path = ['/Users/balaji/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/balaji/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Monterey (12.6),  `ansible-lint 6.8.2 using ansible 2.13.5`

### Relevant log output
The above minimal example works correctly with ansible-lint called directly:

~~~ sh
$ ansible-lint playbooks/playbook.yml
WARNING  Listing 1 violation(s) that are fatal
no-relative-paths: The src argument should not use a relative path. (warning)
playbooks/playbook.yml:5 Task/Handler: Copy the CA certificate


                Rule Violation Summary
 count tag               profile rule associated tags
     1 no-relative-paths shared  idiom (warning)

Passed with safety profile, 3/5 star rating: 0 failure(s), 1 warning(s) on 1 files.
~~~

**Comment by yaegassy** [comment]
Issues that may be relevant.

- <https://github.com/ansible/ansible-language-server/issues/439>

**Comment by balaji-dutt** [comment]
> Issues that may be relevant.
> 
>     * [Warnings are displayed as errors ansible-language-server#439](https://github.com/ansible/ansible-language-server/issues/439)

@yaegassy  it does seem to be similar. Do you want me to close this issue as a dupe of the other one?

**Comment by yaegassy** [comment]
@balaji-dutt I do not think we need to close this issue at this time. Once the fixes and adjustments are complete, I'm sure the vscode-ansible maintainer will close it as needed.

**Comment by balaji-dutt** [comment]
Hi,

I just tested [v1.1](https://github.com/ansible/vscode-ansible/releases/tag/v1.1) of the extension and it appears that the extension now correctly honors `warn_list` parameters in an `.ansible-lint` file.
