### ISSUE TITLE
Access permission issue on the ansible-config dump call when using Win11/WSL/DockerForWindows

### ISSUE THREAD

**Issue by Bengrunt** [ansible/vscode-ansible#669]
### Summary

Ansible extension fails to run because of the ansible-config dump that triggers a permission issue on `/etc/passwd`.

In the console output I find the `docker run` command that is used by the extension. I noticed a `--user=1000` option is used, if I run the command manually it triggers the same error. If I run it manually with the `--user=0` option instead, it works.

I don't know how to set this in the extension settings.
Using `  "ansible.executionEnvironment.containerOptions": "--user=0"` does not seem effective.

### Extension version

1.0.90

### VS Code version

1.72.2

### Ansible Version

```shell
$ ansible --version
ansible [core 2.12.4]
  config file = /home/ben/.ansible.cfg
  configured module search path = ['/home/ben/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ben/tools/virtualenvs/ansible-gitlab-runner/lib/python3.8/site-packages/ansible
  ansible collection location = /home/ben/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ben/tools/virtualenvs/ansible-gitlab-runner/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.1
  libyaml = True
```

### OS / Environment

Windows 11, WSL (Ubuntu 20.04.5 LTS (Focal Fossa)), Ansible lint 6.8.2
Using Docker for Windows v4.12.0
```$ docker --version
Docker version 20.10.17, build 100c701
```

### Relevant log output

```shell
docker run --rm --workdir /home/ben/git/ansible/ansible-gitlab-runner -v /home/ben/git/ansible/ansible-gitlab-runner:/home/ben/git/ansible/ansible-gitlab-runner -e ANSIBLE_FORCE_COLOR=0 --user=1000 --name ansible_language_server_bf2e5f4c-c6d2-46ba-877c-a48712f3ab1d quay.io/ansible/creator-ee:latest ansible-config
dump
/usr/bin/entrypoint: line 42: /etc/passwd: Permission denied
```

**Comment by ansiblejunky** [comment]
Same. I just noticed the error today.
It's causing the extension to show a red line at the top of my `yml` files with the error message:
```
Unexpected error code 1 from execution of: ansible-playbook --syntax-check -i localhost, site.yml ansible-lint
```
Please can you fix this?

**Comment by kbreit** [comment]
I'm seeing a similar problem. This is happening on macOS under Docker (podman doesn't work with navigator). What's interesting is I am not sold this is a VSC problem since I'm getting this with `ansible-navigator`. Problem is `entrypoint` tries to write to `/etc/passwd` for the UID 0. This aligns pretty closely with this issue, but again, I'm not using VSC.

**Comment by ansiblejunky** [comment]
@kbreit If you view the "Output" window in VSCode and select the "Ansible Server" in the Output window (far-right). You'll then see what's really going on. I have had to do this a lot... and was helpful to fix the issue or raise it here again.

**Comment by ssbarnea** [comment]
Can you please test again after pulling the creator-ee container again and checking that you are using the pre-release version of the extension. Good idea to also test the container command yourself. You should not need to customize any arguments passed to the container.
