### ISSUE TITLE
Inconsistent syntax highlighting and autocompletion

### ISSUE THREAD

**Issue by luc-ass** [ansible/vscode-ansible#695]
### Summary

Syntax highlighting is inconsistent and only highlights some modules. Even some modules that are part of the autocompletion (i.e. ansible.builtin.*) are not highlighted in the correct way:

![Bildschirm­foto 2022-11-25 um 20 27 54](https://user-images.githubusercontent.com/3263257/204045655-3fa8dfee-71ba-4059-93f4-4622898ee05c.jpg)

As you can see, `ansible.builtin.apt` and `ansible.builtin.pip` are recognised correctly. `ansible.builtin.docker_prune` and the suggested improvement `community.docker.docker_prune` are not recognised.

On a side note: Is it correct, that only the `ansible.builtin.*` are part of the autocompletion?

### Extension version

v1.0.90

### VS Code version

1.73.1

### Ansible Version

```shell
ansible --version
ansible [core 2.13.5]
  config file = /Users/lucas/Documents/GitHub/ansible/ansible.cfg
  configured module search path = ['/Users/lucas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/6.5.0/libexec/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/lucas/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Apple MacBook Air M1
MacOS Ventura 13.0.1
ansible-lint 6.8.1 using ansible 2.13.5

### Relevant log output

```shell
Path for lint:  /opt/homebrew/bin/ansible-lint
Validating using ansible-lint
Path for lint:  /opt/homebrew/bin/ansible-lint
Validating using ansible-lint
[Info  - 8:36:37 PM] [ansible-lint] [DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names 
to new standard, use callbacks_enabled instead. This feature will be removed 
from ansible-core in version 2.15. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
WARNING  Overriding detected file kind 'yaml' with 'playbook' for given positional argument: /Users/lucas/Documents/GitHub/ansible/docker-maintenance.yml

Passed with production profile: 0 failure(s), 0 warning(s) on 1 files.
```

**Comment by priyamsahoo** [comment]
@luc-ass, auto-completion works for all the ansible collections found in your env. It is undoubtedly not limited to just `ansible.builtin.*`.

But for the first part, `community.*.*` (for all the FQCN's consisting of more than 3 parts), some discussions are going on in the team. Please refer: https://github.com/ansible/vscode-ansible/issues/573

**Comment by luc-ass** [comment]
@priyamsahoo thank you for your feedback! I am embarrassed, that I missed installing the collection first. :blush:

I'll report back/close the issue If this solves my issue.

**Comment by luc-ass** [comment]
`ansible-galaxy collection install community.docker` solved this issue for me. Thanks for pushing me in the right direction!
