### ISSUE TITLE
openvsx extension version outdates

### ISSUE THREAD

**Issue by satirical-eraser** [ansible/vscode-ansible#699]
### Summary

openvsx version is behind ms marketplace

### Extension version

v1.0.90

### VS Code version

1.73.1

### Ansible Version

```shell
n/a
```

### OS / Environment

n/a

### Relevant log output

```shell
n/a
```

**Comment by ssbarnea** [comment]
That is not true, latest versions are both the same 103, the difference that you say is related to how the two websites display the pre-releases.
