### ISSUE TITLE
VSCode has incorrect schema URL in config

### ISSUE THREAD

**Issue by s3638844** [ansible/vscode-ansible#709]
##### Summary

When using the vsode plugin it has a typo in the schema URL causing it to fail to fetch the schema
schema URL seems that it should be: 
https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/tasks.json

However, in the plugin it refs:
https://raw.githubusercontent.com/ansible/ansiblelint/main/src/ansiblelint/schemas/tasks.json

**Comment by ssbarnea** [comment]
Are you sure you tried the pre-release version? I am not seeing the bug inside the code which makes be think that maybe you are using the outdated last release.

**Comment by icodeforyou-dot-net** [comment]
I just ran into what looks to me like the same issue. It got resolved by updating the outdated VSCode extension.
