### ISSUE TITLE
regression: yarn webpack reports Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ssbarnea** [ansible/vscode-ansible#748]
Introduction of telemetry introduce a regression on webpack where we can see this WARNING, which sounds more serious than a warning based on the "Critical dependency" part of it:

```
C:\Users\sorin\c\vscode-ansible>yarn run webpack
30 assets
533 modules

WARNING in ./node_modules/@redhat-developer/vscode-redhat-telemetry/lib/services/configurationManager.js 114:19-38
Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (C:\Users\sorin\c\vscode-ansible\node_modules\webpack\lib\dependencies\ContextDependency.js:102:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\sorin\c\vscode-ansible\node_modules\webpack\lib\Compilation.js:3132:24)
    at C:\Users\sorin\c\vscode-ansible\node_modules\webpack\lib\Compilation.js:2729:28
    at _next2 (eval at create (C:\Users\sorin\c\vscode-ansible\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\sorin\c\vscode-ansible\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:62:1)
    at C:\Users\sorin\c\vscode-ansible\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:385:11
    at C:\Users\sorin\c\vscode-ansible\node_modules\neo-async\async.js:2830:7
    at Object.each (C:\Users\sorin\c\vscode-ansible\node_modules\neo-async\async.js:2850:39)
    at C:\Users\sorin\c\vscode-ansible\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:361:18
    at C:\Users\sorin\c\vscode-ansible\node_modules\neo-async\async.js:2830:7
 @ ./node_modules/@redhat-developer/vscode-redhat-telemetry/lib/vscode/redhatService.js 40:31-74
 @ ./node_modules/@redhat-developer/vscode-redhat-telemetry/lib/index.js 4:24-57
 @ ./src/utils/telemetryUtils.ts 27:14-70
 @ ./src/extension.ts 32:25-58

webpack 5.75.0 compiled with 1 warning in 12826 ms
```

This will be produced on any platform and I have no clue what is effectively causing it but it can easily be seen that it is related to `@redhat-developer/vscode-redhat-telemetry`.

**Comment by ssbarnea** [comment]
@ganeshrn Once you fix that, I will add another change that makes webpack warnings be treated as errors, so we don't introduce more regressions accidentally. It seems that https://stackoverflow.com/questions/60092487/with-webpack-is-it-possible-to-force-warnings-to-be-treated-as-errors should help me do that.

Maybe @fbricon could help on this issue as he is the brain behind telemetry extension.

**Comment by fbricon** [comment]
So, vscode-xml already webpacks vscode-redhat-telemetry and works fine. I checked the same warning is produced.
My guess is this is caused by this expression: https://github.com/redhat-developer/vscode-redhat-telemetry/blob/main/src/services/configurationManager.ts#L93

I'm not a JS expert, but I think it's fine. Dunno if there's a way to tell webpack to SFTU about certain statements. 
Now if you know a clever way to rewrite the same thing differently, lemme know.

**Comment by ssbarnea** [comment]
That part is clearly going to help us find a solution for it. What is bit weird is that I did not see any warning while compiling the telemetry package locally. Maybe we could add a script that does use webpack on it just to test for this? I am not sure if that warning is really a reason to concern but if we can address it, it would be better.

**Comment by fbricon** [comment]
vscode-redhat-telemetry isn't webpacked. Some bits depend on nodejs, some others on DOM. Im not sure webpacking it won't cause issues down the line, but again not a JS expert.

Anyways, https://github.com/redhat-developer/vscode-redhat-telemetry/pull/23/files#diff-3dbf6e739072174d75c3247910cbd0ac5f8972a7b0cea0ac00336526b474eaf5R93 should fix the current issue.

Please try [@redhat-developer/vscode-redhat-telemetry 0.5.3](https://www.npmjs.com/package/@redhat-developer/vscode-redhat-telemetry/v/0.5.3)

**Comment by ssbarnea** [comment]
For reference the issue seems to be caused by https://github.com/webpack/webpack/issues/13865

**Comment by fbricon** [comment]
yeah I'm seeing this too. FFS

**Comment by ssbarnea** [comment]
At least I am glad I am not the only one affected. It is quite confusing. I looked at the code and I was hoping we might have a way to bypass the loading of the default config but apparently that is not possible. I wonder if we should not better avoid using a variable and instead go for a static string. In the end webpack is expected to just load that data at compile time, so there is nothing dynamic about that. If anyone needs custom config, they can load it after, but the default should be static.

**Comment by fbricon** [comment]
try 0.5.4 now
