### ISSUE TITLE
Disabling Lightspeed in settings does not disable features

### ISSUE THREAD

**Issue by timfallmk** [ansible/vscode-ansible#859]
### Summary

With the introduction of [new Lightspeed integration in 2.0](https://github.com/ansible/vscode-ansible/discussions/855) I'm now getting bugged to "log in to ansible lightspeed to use ansible" on every open window. I have the "Lightspeed" enable option unchecked in the settings.
![image](https://user-images.githubusercontent.com/5316117/232562592-ba1ca03a-d5b1-44af-9d97-effba89e953c.png)
![image](https://user-images.githubusercontent.com/5316117/232562830-26907804-388c-4400-85bf-43794ef5286a.png)

There may be other parts of Lightspeed that are not being disabled when the user explicitly does not enable them.

### Extension version

v2.0.58

### VS Code version

1.77.3

### Ansible Version

```shell
ansible [core 2.14.4]
  config file = /Users/tfall/Code/stand-configuration/ansible.cfg
  configured module search path = ['/Users/tfall/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/7.4.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/tfall/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/7.4.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Ventura 13.3.1
ansible-lint 6.14.6 using ansible 2.14.4

**Comment by rothfralick** [comment]
Same here.  Very annoying.
Ansible extension v2.0.58
VSCode 1.77.3
Windows 11

**Comment by Zombiefleischer** [comment]
Also autocompletion is not working with this new version
Ansible extension v2.0.58
VSCode 1.77.3
Linux Debian

**Comment by ganeshrn** [comment]
@timfallmk Thanks for raising the issue, we will work on the fix.

@Zombiefleischer 

> Also autocompletion is not working with this new version


Autocompletion should work irrespective of Lightspeed is enabled or disabled.
Is it possible for you to share a screen recording?
Also the debug logs, you can refer [this](https://www.youtube.com/watch?v=vfIbIIbtQYI) to get the debug logs

**Comment by Zombiefleischer** [comment]
I went back to v1.2.44 for the time being and to get the screen recording I switched back to the latest version (v2.0.58) and it automagically fixed itself. I don't know what went wrong, but it works fine now. Sorry for the inconvenience.

**Comment by lcrownover** [comment]
I assume based on response that this is a known issue that will be resolved, but I figured I'd just add to the dogpile.

That (1) is annoying!

**Comment by rubin55** [comment]
The message is:

    Sign in with Ansible Lightspeed to use Ansible(1)

Question: Is the intention of this to communicate the `Ansible` extension won't work unless you log in using `Ansible Lightspeed`?

**Comment by ganeshrn** [comment]
@rubin55 Ansible extension will continue to work irrespective of user has logged in to the Ansible Lightspeed service. I agree the message is misleading and we can change it.

**Comment by safderali5** [comment]
very annoying and no way to disable this :-(

**Comment by harwinds** [comment]
I actually unchecked the `Accounts` from get rid of the annoying `(1)` for the Ansible extension.

![image](https://user-images.githubusercontent.com/49625802/234870574-94fce4b6-0b81-48b9-959f-c38f111568f1.png)

**Comment by harwinds** [comment]
I actually unchecked the `Accounts` from the side bar to get rid of the annoying `(1)` for the Ansible extension.

![image](https://user-images.githubusercontent.com/49625802/234870574-94fce4b6-0b81-48b9-959f-c38f111568f1.png)

**Comment by MrSteve81** [comment]
I can also confirm when i am on v2.0.58 the auto complete for modules does not work 
![image](https://user-images.githubusercontent.com/92482471/234957114-1ed51214-d898-48e3-890c-b6d24e3ceb09.png)
but when i switch back to Ansible
v1.2.44 it works

**Comment by MrSteve81** [comment]
> Also autocompletion is not working with this new version Ansible extension v2.0.58 VSCode 1.77.3 Linux Debian

I can also confirm when i am on v2.0.58 the auto complete for modules does not work
![image](https://user-images.githubusercontent.com/92482471/234957699-b729f512-96b6-4f17-bc52-ec649f9bb2cc.png)
but when i switch back to Ansible
v1.2.44 it works

**Comment by ganeshrn** [comment]
@MrSteve81  The autocompletion feature should work irrespective of if you sign to Lightspeed service or not. Please refer to my comment https://github.com/ansible/vscode-ansible/issues/859#issuecomment-1514740398. After updating the version try reloading VSCode. It might be an intermittent issue as reported here https://github.com/ansible/vscode-ansible/issues/859#issuecomment-1514779167

**Comment by dszryan** [comment]
"ansible.lightspeed.URL": "",

seemed to have reduced the annoyance

**Comment by huyz** [comment]
> "ansible.lightspeed.URL": "",

hehe that's the kind of workaround that will make it harder to adopt this new feature when it is actually available—perhaps devs will learn from that for next time.

**Comment by mousedownmike** [comment]
Setting `"ansible.lightspeed.URL": "",` didn't remove the Sign In badge for me on Linux and MacOS.  It looked like it did when I first made the change, but the badge came back after subsequent reloads.

**Comment by vv0s4k** [comment]
> "ansible.lightspeed.URL": "",
> 
> seemed to have reduced the annoyance

Had a hard time trying to find out why Agent stopped working in Cursor. It was just in a permanent "Generating" state. I did not have such an issue when I was writing Golang code, but I encountered this issue every time I switched to an Ansible repo. You just saved my day. TY a lot.
