### ISSUE TITLE
Ansible extension not respecting exclude_paths from .ansible-lint configuration file

### ISSUE THREAD

**Issue by jonbackhaus-mt** [ansible/vscode-ansible#880]
### Summary

I have a `.ansible-lint` file in my `ansible` directory, which owns all my playbooks, etc. and follows a (modified) standard directory layout: 

```
######################### # DIRECTORIES # #########################
filter_plugins/   # custom filter plugins
inventories/      # all inventory files live here, organized by deployment (e.g. "prod")
library/          # if any custom modules, put them here (optional)
module_utils/     # if any custom module_utils to support modules, put them here (optional)
roles/            # reusable "role" modules; see below for details and structure
tasks/            # reusable "task" modules

######################### # FILES # #########################
.ansible-lint     # linter config.
ansible.cfg       # project configuration file
...
```

Here's my `.ansible-lint` config. file: 

```
exclude_paths:
  - roles/

use_default_rules: true

# Enable checking of loop variable prefixes in roles
loop_var_prefix: "__"

# This makes linter to fully ignore rules/tags listed below
skip_list:
  - name

# Define custom bindings
kinds:
  - vars: "**/inventories/**/*.{yml,yaml}"
```

If I open a playbook that references an Ansible role, I get a validation error in VS Code, which should not happen based on my `exclude_paths` rule: 
![Screenshot 2023-05-09 at 10 01 45 AM](https://github.com/ansible/vscode-ansible/assets/100298177/5ae76c62-3b9a-44ac-a340-8d553b13f528)

The rest of my rules seem to be working fine and the config. works as expected if I run a manual validation with `ansible-lint` from the command line.

### Extension version

2.0.58

### VS Code version

1.78.0

### Ansible Version

```shell
ansible [core 2.14.5]
  config file = /Users/jonathanbackhaus/Projects/ise/dee-deployments/ansible/ansible.cfg
  configured module search path = ['/Users/jonathanbackhaus/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/jonathanbackhaus/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

macOS Ventura 13.3.1 (a)
Python 3.11.2
ansible-lint 6.16.0 using ansible 2.14.5

**Comment by MallocArray** [comment]
There was an issue with ansible-lint 6.16.2 at least that was not properly using the excluded paths in .ansible-config and maybe it was present in this version as well.
If you haven't already, try upgrading to ansible-lint 6.17.0 or later and see if it is behaving as expected

**Comment by jonbackhaus-mt** [comment]
Yep! Finally works as expected! One note: I had to preface my `exclude_paths` entries with "ansible/", which I wouldn't have expected. Are these paths intended to be relative to the `.ansible-lint` file (which was my assumption) or relative to the repository root (which is the current behavior)?

**Comment by JohnRDOrazio** [comment]
> Yep! Finally works as expected! One note: I had to preface my `exclude_paths` entries with "ansible/", which I wouldn't have expected. Are these paths intended to be relative to the `.ansible-lint` file (which was my assumption) or relative to the repository root (which is the current behavior)?

Adding the root path of the project worked shortly to prevent linting of external installed roles, but now it's back to linting them. The `exclude_paths` directive does not seem to be very stable...

**Comment by jkossis** [comment]
I'm seeing this issue pop up again.

@JohnRDOrazio or @MallocArray, did you ever figure this out?
