### ISSUE TITLE
[Feature Request] New setting to scan for modelines only on file open

### ISSUE THREAD

**Issue by lonix1** [ansible/vscode-ansible#888]
### Problem

I noticed:
1. if a file with the `code:language=ansible` modeline is opened, then it is detected as an ansible file
2. if a file without the modeline is opened, then the modeline is added and the file is saved, then it is re-detected as an ansible file

So (2) means that the extension is rereading every single file on every save. That seems very wasteful. VSCode already has many builtins and extensions hammering our resources, especially in certain environments (csharp extension!).

### Solution

Please consider adding a setting that if set, will scan for modelines only on file open.

**Comment by ssbarnea** [comment]
AFAIK we never write the modeline, we only read it.
