### ISSUE TITLE
Auto suggestions doesn't work

### ISSUE THREAD

**Issue by NikSudo** [ansible/vscode-ansible#915]
### Summary

MacOS 13.3.1 (a) 

Doesn't work autosuggestions.
ansible-language-server 1.0.4 version 
ansible-lint --version
ansible-lint 6.14.4 using ansible 2.15.0

neovim working fine with the language-server version as well as pycharm.

### Extension version

v2.2.69

### VS Code version

1.77.3

### Ansible Version

```shell
❯ ansible --version
ansible [core 2.15.0]
  config file = /Users/nsumin/Projects/<commersion_secure>/deployment/ansible/ansible.cfg
  configured module search path = ['/Users/nsumin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.10/site-packages/ansible
  ansible collection location = /Users/nsumin/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.10.12 (main, Jun  7 2023, 00:45:35) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/usr/local/opt/python@3.10/bin/python3.10)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

MacOS 13.3.1 (a)

**Comment by adeqecil** [comment]
Yes, I'm facing this issue too with the same version unless the ansible-lint(6.17.0)

I tried pressing `Ctrl + Space` to trigger auto suggestion but it doesn't appear anything.

**Comment by NikSudo** [comment]
Working after vscode update, but seems like you have a conflict with [spell-checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by adeqecil** [comment]
> 

What is the vscode update version @NikSudo ?
mine is below, still suggestion not working
![image](https://github.com/ansible/vscode-ansible/assets/43349767/1e8d9a78-1d28-4f0d-aea6-ff831e3361ee)

**Comment by ajinkyau** [comment]
@NikSudo just wanted to confirm if this works with the recent updates to the extension and language-server.
@adeqecil Did you try updating extension and vscode to the latest version?
