### ISSUE TITLE
Ansible lightspeed

### ISSUE THREAD

**Issue by nadiofortunato** [ansible/vscode-ansible#935]
### Summary

When I press the ansible button to log on to my GitHub account a get an error "unable to parse decrypted password".
Currently using ansible 2.15.1
<img width="1433" alt="Screenshot 2023-06-28 at 14 06 44" src="https://github.com/ansible/vscode-ansible/assets/25823684/b854dc0d-22c6-4a34-bbb5-20bb28188e31">

### Extension version

Ansible 

### VS Code version

Version: 1.79.2 

### Ansible Version

```shell
ansible [core 2.15.1]
  config file = /Users/nadiofortunato/Desktop/Automation/playbooks/ansible.cfg
  configured module search path = ['/Users/nadiofortunato/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/nadiofortunato/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.1 (main, Dec 23 2022, 09:28:24) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

Mac OS Ventura 

### Relevant log output

```shell
Unable to parse decrypted password
```

**Comment by ganeshrn** [comment]
@nadiofortunato This is any issue in your environment. Open the `keychain Access` search and delete the vscode ansible related passwords. After that retry to login.
