### ISSUE TITLE
Ansible Lightspeed - Failed to refresh token. Please log out and log in again

### ISSUE THREAD

**Issue by seulsale** [ansible/vscode-ansible#969]
### Summary

I get this error message but don't see any way to re-authenticate in the extension panel. It still shows up as "Logged in as {{ user }}"
![image](https://github.com/ansible/vscode-ansible/assets/20617822/11606369-ab43-487d-ae7b-9d992ed0c38c)

![image](https://github.com/ansible/vscode-ansible/assets/20617822/16b2b611-c310-44b0-922f-29c7ac7bd2e6)

The error prompt appears any time I should be getting a code suggestion (hitting enter after setting a task name).

### Extension version

v2.7.98

### VS Code version

1.81.0

### Ansible Version

```shell
ansible [core 2.14.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/seulsale/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/seulsale/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
```

### OS / Environment

- Fedora 38

**Comment by priyamsahoo** [comment]
You can log out by clicking on the user icon on the activity bar. Once logged out, you can log in again.
Here is where you can find it:

![Untitled](https://github.com/ansible/vscode-ansible/assets/42550351/cf44f77a-5de5-4fc6-ba24-c1b26c8fa86b)

**Comment by seulsale** [comment]
@priyamsahoo that worked, thanks! 

I still think it would be useful to catch that error and prompt the user to re-authenticate. Or give them directions on how they can log in again using this menu.
