### ISSUE TITLE
yamllint on regular yaml files

### ISSUE THREAD

**Issue by skwde** [ansible/vscode-ansible#975]
### Problem

It is mentioned by @ssbarnea here https://github.com/redhat-developer/yaml-language-server/issues/262#issuecomment-784104474 that `yamllint` execution is provided by this extension.

Sadly I cannot find a way to do this.

Also <https://github.com/ansible/vscode-ansible/issues/129> was not really helpful.

So how do I run `yamllint` on regular `yaml` files (outside the yaml context).

### Solution

A description of settings required to run `yamllint` on regular `yaml` files (outside the ansible context).

### Alternatives

There the extension <https://marketplace.visualstudio.com/items?itemName=fnando.linter> but sadly it looks as if it doesn't support venv's (<https://github.com/fnando/vscode-linter/issues/25>) but rather requires the linters to be available in `PATH`.

There is also the possibility to run a vscode task (<https://github.com/ansible/vscode-ansible/issues/130#issuecomment-875713522>) but this is also not really satisfying.

**Comment by ssbarnea** [comment]
Closing as this is outside the scope of the project but noting that if someone makes a PR to improve the documentation, we will welcome it.
