### ISSUE TITLE
Hey! Any chances for this plugin to come in to pycharm ? ^^

### ISSUE THREAD

**Issue by ginolegigot** [ansible/vscode-ansible#982]
### Problem

Need this plugin in pycharm, the ansible plugin in pycharm is kinda outdated and more or less not maintained since  awhile, this one is a beast on vscode but i'd love to have the same in pycharm

### Solution

hard to say ^^

**Comment by ssbarnea** [comment]
If someone writes an extension for it based on our language server, we will work with them to ensure it works but we have no plans of writing and maintaining such an extension ourselves.

**Comment by ginolegigot** [comment]
Oki thanks for your reply, good day!
