### ISSUE TITLE
syntax-check[specific]

### ISSUE THREAD

**Issue by skwde** [ansible/vscode-ansible#986]
### Summary

`syntax-check[specific]` not shown by extension.

Following pic show the problem:

![Screenshot 2023-09-29 at 11 36 16](https://github.com/ansible/vscode-ansible/assets/26454702/0e4d7b4c-99f7-440f-97c9-6d01beb48d9f)

Possibly related: <https://github.com/ansible/vscode-ansible/issues/894>

### Extension version

v2.7.98

### VS Code version

1.82.2 Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d

### Ansible Version

```shell
$ ansible --version
ansible [core 2.15.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['<home>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = <mambaforge location>/envs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = <own collections>/usr/share/ansible/collections:/usr/share/ansible/collections
  executable location = <mambaforge location>/envs/ansible/bin/ansible
  python version = 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0] (<mambaforge location>/envs/ansible/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### OS / Environment

MacOS 13.5.2 (22G91); ansible-lint version 6.17.2

**Comment by ssbarnea** [comment]
I am able to reproduce this bug with this minimal example:
```
---
- name: Example
  hosts: "{{ hostsvars['sss'] }}"
  tasks: []
```
