### ISSUE TITLE
Auto matching based on file beginning with `---`

### ISSUE THREAD

**Issue by cidrbl0ck** [ansible/vscode-ansible#987]
### Problem

So for the past year or more since using VSCOde for writing Ansible content and having the Ansible extension installed I have to manually match Ansible to the files as I create them. 
Not knowing exactly where the Ansible extensions reach ends in terms of proper yaml format.. I also use the RH Yaml extension. Possibly having to match by hand is due to having both extensions, or due to not using some specific file naming convention.  In any case it's an annoyance really.

### Solution

So since Ansible playbooks at least, typically start with three hashes `---`, I believe that having the ability to match based on the presence of those in line 1 characters 1-3, would be a super function!

I'm a strict hasher in all my ansible yml files, and I believe that having a feature like this would be easier to use than adhering to some naming convention, plus help ensure a bit of consistency.

### Alternatives

Manually clicking the drop down and changing from YAML to Ansible.

**Comment by jorneilander** [comment]
Considering `---` is not specific to Ansible but YAML, I'd argue this is not an ideal solution. My workaround is to set this globally:

```JSON
"files.associations": {
    "**/*_vars/**/*.y*ml": "ansible",
    "**/*ansible*/**/*.y*ml": "ansible",
    "**/defaults/**/*": "ansible",
    "**/handler/*.y*ml": "ansible",
    "**/inventory/*/*": "ansible",
    "**/playbooks/**/*.y*ml": "ansible",
    "**/roles/**/*.y*ml": "ansible",
    "**/tasks/**/*.y*ml": "ansible",
    "**/vars/**/*.y*ml": "ansible",
    "*.y*ml": "yaml"
  }
```

There's still the odd file here and there, but in 99,9% of the time it works.

**Comment by ssbarnea** [comment]
`---` are YAML feature and they have nothing to do with Ansible itself. We will not add any features that would require looking at `---` separator. 

https://github.com/ansible/vscode-ansible/blob/main/README.md#language-association-to-yaml-files

**Comment by cidrbl0ck** [comment]
Ahh I was entirely unaware.. I've been using --- in all of mine since the file format is supposed to be yaml. I'd argue that it's a smidge confusing that playbooks are yaml but not strict yaml. 
Eh, either way thanks for the clarification.
